"""Write data/recon/b35/B35_spec.yaml (the tan house in R03) for build_hero.py.

    ~/.venvs/recon/bin/python gen_house.py && ~/.venvs/recon/bin/python build_hero.py data/recon/b35/B35_spec.yaml

Footprint and ridge height from its LOD1 fit (buildings_lod1.yaml: 12.0 x 6.8 m, 7.1 m); the look
from the drone video (B04 frame 2, B07): two storeys of tan stucco under a brown hip roof with a
shallow overhang, two windows and a door on the street face, one window per floor at the ends.
Openings follow that view, not a survey.
"""
import yaml
from _paths import R

b = next(x for x in yaml.safe_load(open(R / "buildings_lod1.yaml"))["buildings"] if x["id"] == "B35")
import numpy as np
X, Y = max(b["size_m"]), min(b["size_m"]); RIDGE = b["height_m"]; EAVE, FH = RIDGE - 1.8, (RIDGE - 1.8) / 2
yaw = b["yaw_deg"] + (90 if b["size_m"][1] > b["size_m"][0] else 0); th = np.radians(yaw)
o = np.array(b["at"]) - np.array([[np.cos(th), -np.sin(th)], [np.sin(th), np.cos(th)]]) @ [X / 2, Y / 2]
win = lambda at: {"at": at, "w": 1.1, "sill": 0.9, "h": 1.2}
parts = [{"box": {"name": "slab_0", "min": [0, 0, 0], "max": [X, Y, 0.15]}},
         {"box": {"name": "slab_1", "min": [0, 0, FH], "max": [X, Y, FH + 0.2]}},
         {"box": {"name": "ceiling", "min": [0, 0, EAVE - 0.15], "max": [X, Y, EAVE]}}]
for f, (z0, z1) in enumerate(((0.15, FH), (FH + 0.2, EAVE - 0.15))):
    parts += [
        {"wall": {"name": f"wall_ylo_{f}", "from": [0, 0], "to": [X, 0], "z": [z0, z1],
                  "openings": [win(1.5), win(X - 2.6)] if f else [win(1.5), {"at": X / 2, "w": 1.0, "h": 2.1}]}},
        {"wall": {"name": f"wall_yhi_{f}", "from": [0, Y], "to": [X, Y], "z": [z0, z1], "openings": [win(X / 2 - 0.55)]}},
        {"wall": {"name": f"wall_xlo_{f}", "from": [0, 0], "to": [0, Y], "z": [z0, z1], "openings": [win(Y / 2 - 0.55)]}},
        {"wall": {"name": f"wall_xhi_{f}", "from": [X, 0], "to": [X, Y], "z": [z0, z1], "openings": [win(Y / 2 - 0.55)]}}]
parts.append({"hip": {"name": "roof", "min": [-0.4, -0.4, EAVE], "max": [X + 0.4, Y + 0.4, RIDGE], "mat": "roof_brown"}})
parts.append({"stair": {"name": "stair", "from": [X - 1.2, 1.0, 0.15], "to": [X - 1.2, Y - 1.2, FH + 0.2], "width": 0.9, "mat": "wood"}})
spec = {"id": "B35", "name": "tan_house", "semantic": "building", "default_mat": "stucco",
        "origin": [round(float(o[0]), 3), round(float(o[1]), 3), b["ground_z"]], "yaw_deg": round(float(yaw), 2), "parts": parts,
        "lights": [{"rect": [0.3, 0.3, X - 0.3, Y - 0.3], "ceiling": z, "spacing": 5} for z in (FH, EAVE - 0.15)]}
out = R / "b35/B35_spec.yaml"; out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# generated by gen_house.py -- edit that, not this\n" + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=200))
print(f"{len(parts)} parts -> {out}")
