"""Write data/recon/s01/S01_spec.yaml (the drill tower) for build_hero.py.

    ~/.venvs/recon/bin/python gen_drill_tower.py && ~/.venvs/recon/bin/python build_hero.py data/recon/s01/S01_spec.yaml

Footprint/height off the tile mesh (body 6.7 x 8.2 m at 45 deg, top 20.3 m ->
6 floors x 3.3 m). Look off the drone video (A04 frame 5, B05): metal-clad, ribbed on two faces
and flat grey on the other two, closed dark window panels (two per floor per face), a wide
top-floor opening on two faces, an external switchback stair in a narrow steel frame on one side (landings every floor). Panel
positions follow the pattern -- they are not surveyed.
"""
from pathlib import Path
import numpy as np, yaml
from _paths import R

FH, NF, X, Y = 3.3, 6, 6.7, 8.2
# faces as filmed (A04 frame 5, B05): ylo/yhi clad in ribbed metal, xlo/xhi flat grey; the "windows" are closed dark
# panels, two per floor per face, 3 cm proud; the only openings are a wide top-floor one on yhi and xhi and a door
FACE = {"ylo": ([0, 0], [X, 0], "metal_ribbed"), "yhi": ([0, Y], [X, Y], "metal_ribbed"),
        "xlo": ([0, 0], [0, Y], "metal_grey"), "xhi": ([X, 0], [X, Y], "metal_grey")}
parts = [{"box": {"name": "slab_0", "min": [0, 0, 0], "max": [X, Y, 0.2]}}]
for f in range(NF):
    z0, z1 = f * FH + 0.2, (f + 1) * FH
    top = f == NF - 1
    for k, (a, b, mat) in FACE.items():
        L = abs(b[0] - a[0]) + abs(b[1] - a[1])
        ops = [{"at": 0.8, "w": L - 1.6, "sill": 0.6, "h": 2.0}] if top and k in ("yhi", "xhi") else \
              [{"at": 0.8, "w": 1.0, "h": 2.1}] if f == 0 and k == "xlo" else []
        parts.append({"wall": {"name": f"wall_{k}_{f}", "from": a, "to": b, "z": [z0, z1], "mat": mat, "openings": ops}})
        if top and k in ("yhi", "xhi"): continue
        out = {"ylo": (0, -1), "yhi": (0, 1), "xlo": (1, -1), "xhi": (1, 1)}[k]                   # (axis along, outward sign)
        for c in (0.2 * L, 0.8 * L - 1.2):
            if f == 0 and k == "xlo" and c < 2: continue                                          # the door
            lo, hi = [0.0, 0.0, z0 + 0.9], [0.0, 0.0, z0 + 2.1]
            al, ac = (0, 1) if k[0] == "y" else (1, 0)
            lo[al], hi[al] = c, c + 1.2
            wall = a[ac]; lo[ac], hi[ac] = sorted((wall + out[1] * 0.125, wall + out[1] * 0.155))
            parts.append({"box": {"name": f"panel_{k}_{f}_{int(c)}", "min": lo, "max": hi, "mat": "panel_dark"}})
    parts.append({"box": {"name": f"slab_{f + 1}", "min": [0, 0, z1], "max": [X, Y, z1 + 0.2]}})
# the slim steel frame on the xlo face (A04 frame 5): four posts, a landing at the first floor and one at the roof, a ladder
# the external switchback stair on the xlo face (the tiles' zigzag; A04 frames 16-18: a narrow steel frame with a railed
# landing at every floor and a top landing): a frame 1.5 m deep along the face's whole width, landings alternating
# ends, one flight per storey between them, banisters, and an outer rail up the open side
D, L0, L1 = 1.5, 0.15, Y - 0.15                                          # frame depth, the face's ends
for i, x in enumerate((-D, -0.1)):
    for j, y in enumerate((L0, L1)):
        parts.append({"box": {"name": f"post_{i}{j}", "min": [x - 0.08, y - 0.08, 0], "max": [x + 0.08, y + 0.08, NF * FH + 1.3], "mat": "steel"}})
LD = 1.5                                                                 # landing length along the face
for f in range(NF + 1):
    z = f * FH + 0.2; at_lo = f % 2 == 0
    ya, yb = (L0, L0 + LD) if at_lo else (L1 - LD, L1)
    parts.append({"box": {"name": f"landing_{f}", "min": [-D, ya, z - 0.1], "max": [0, yb, z], "mat": "grating"}})
    parts.append({"rail": {"name": f"rail_landing_{f}_out", "from": [-D, ya], "to": [-D, yb], "z": z, "mat": "steel"}})
    parts.append({"rail": {"name": f"rail_landing_{f}_end", "from": [-D, L0 if at_lo else L1], "to": [0, L0 if at_lo else L1], "z": z, "mat": "steel"}})
    parts.append({"box": {"name": f"landing_beam_{f}", "min": [-D, ya, z - 0.3], "max": [0, ya + 0.12, z - 0.1], "mat": "steel"}})
    parts.append({"box": {"name": f"landing_beam2_{f}", "min": [-D, yb - 0.12, z - 0.3], "max": [0, yb, z - 0.1], "mat": "steel"}})
    if f < NF:                                                           # the flight up to the next landing, at the other end
        y0, y1 = (L0 + LD, L1 - LD) if at_lo else (L1 - LD, L0 + LD)
        parts.append({"stair": {"name": f"flight_{f}", "from": [-D / 2, y0, z], "to": [-D / 2, y1, z + FH], "width": 1.1, "mat": "grating", "handrails": True}})
spec = {"id": "S01", "name": "drill_tower", "semantic": "building", "origin": [3.556, -515.233, 57.14], "yaw_deg": 45.0, "parts": parts,
        "lights": [{"rect": [0.3, 0.3, X - 0.3, Y - 0.3], "ceiling": NF * FH, "spacing": 4.5}]}          # only the top floor is open
out = R / "s01/S01_spec.yaml"; out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# generated by gen_drill_tower.py -- edit that, not this\n" + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=200))
print(f"{len(parts)} parts -> {out}")
