"""Write data/recon/b03/B03_spec.yaml (Chancellor's Plaza strip mall) for build_hero.py.

    ~/.venvs/recon/bin/python gen_strip_mall.py && ~/.venvs/recon/bin/python build_hero.py data/recon/b03/B03_spec.yaml

Measured off a 1 m roof-height grid of the tile mesh over the LOD1 footprint
(15.0 x 24.0 m, yaw 47.6, walls 5 m): five units along local y, walls at
y = 0 / 4.2 / 8.7 / 14.7 / 19.2 / 24.0. Roof state per unit, from the grid:
  U1 sagged to ~4 m, U2 gone (partition stubs standing at x 5 and 10),
  U3 intact at 5 m, U4 pancaked (4 m at its far wall sloping to 2 m),
  U5 intact over x > 10.4 only, the rest collapsed to 2-3 m.
Facade from image (5).png: storefront on the x = 15 face (door + glazing per
unit, glass gone), a back door per unit. Openings follow that pattern, not a survey.
"""
from pathlib import Path
import yaml
from _paths import R

X, H = 15.0, 5.0
walls_y = [0, 4.2, 8.7, 14.7, 19.2, 24.0]
parts = [{"box": {"name": "floor", "min": [0, 0, 0], "max": [X, 24.0, 0.15]}}]
for i, (y0, y1) in enumerate(zip(walls_y, walls_y[1:])):
    w = y1 - y0
    # storefront (x = X) and back (x = 0) of this unit
    parts.append({"wall": {"name": f"front_u{i + 1}", "from": [X, y0], "to": [X, y1], "z": [0.15, H],
                           "openings": [{"at": 0.5, "w": 1.2, "h": 2.4}, {"at": 2.0, "w": w - 2.5, "sill": 0.6, "h": 2.0}]}})
    parts.append({"wall": {"name": f"back_u{i + 1}", "from": [0, y0], "to": [0, y1], "z": [0.15, H],
                           "openings": [{"at": w / 2 - 0.5, "w": 1.0, "h": 2.1}]}})
for j, y in enumerate(walls_y):                                   # end walls + party walls (x runs 0..X)
    ops = [{"at": 4.0, "w": 1.0, "sill": 1.0, "h": 1.0}, {"at": 10.0, "w": 1.0, "sill": 1.0, "h": 1.0}] if y in (0, 24.0) else []
    parts.append({"wall": {"name": f"cross_{j}", "from": [0, y], "to": [X, y], "z": [0.15, H], "openings": ops}})
roof = lambda n, x0, x1, y0, y1, z: {"box": {"name": n, "min": [x0, y0, z - 0.2], "max": [x1, y1, z]}}
parts += [
    roof("roof_u1_sagged", 0, X, 0, 4.2, 4.0),
    {"box": {"name": "u2_stub_a", "min": [4.9, 4.2, 0.15], "max": [5.1, 8.7, H]}},
    {"box": {"name": "u2_stub_b", "min": [9.9, 4.2, 0.15], "max": [10.1, 8.7, H]}},
    roof("roof_u3", 0, X, 8.7, 14.7, H),
    # U4 pancake: stepped slab, 4 m at the U5 wall down to 2 m at the U3 wall
    roof("roof_u4_step3", 0, X, 17.7, 19.2, 4.0), roof("roof_u4_step2", 0, X, 16.2, 17.7, 3.0), roof("roof_u4_step1", 0, X, 14.7, 16.2, 2.0),
    roof("roof_u5_back", 10.4, X, 19.2, 24.0, H),
    roof("u5_collapse_a", 1.0, 4.5, 19.5, 23.5, 3.0), roof("u5_collapse_b", 4.5, 10.4, 19.5, 23.5, 2.0),
    {"box": {"name": "fascia", "min": [X, 0, 3.6], "max": [X + 0.8, 24.0, 4.4]}},   # the sign band over the storefronts
]
spec = {"id": "B03", "name": "strip_mall", "semantic": "building", "origin": [100.0, -426.05, 57.84], "yaw_deg": 47.6, "parts": parts}
out = R / "b03/B03_spec.yaml"; out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# generated by gen_strip_mall.py -- edit that, not this\n" + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=200))
print(f"{len(parts)} parts -> {out}")
