"""Write data/recon/b06/B06_spec.yaml (the south warehouse) for build_hero.py.

    ~/.venvs/recon/bin/python gen_warehouse.py && ~/.venvs/recon/bin/python build_hero.py data/recon/b06/B06_spec.yaml

Read off the ortho in the LOD1 frame (centre (159.94,-499.27), yaw 47.7; u along
the long side, v across): roof u -20.5..20.3, v -15.2..15.7; ridge at u = 0
running along v, eaves 6.0 m, ridge 7.65 m (tile height). Blue canopy over the
+v face for u -12.6..12.4, with two paths running up to it -> two bay doors
under it (positions follow the paths, sizes guessed 4.5 x 4.5). Central walkway
+ accessible bays on the -v face -> main entrance (double door) at u 0. Walled
equipment yard (1.8 m, open top) off the -u end, u -26..-20.5, v 5..16.
Interior: one open hall. Nothing inside is known.
"""
from pathlib import Path
import numpy as np, yaml
from _paths import R

U0, U1, V0, V1, EAVE, RIDGE = -20.5, 20.3, -15.2, 15.7, 6.0, 7.65
X, Y = U1 - U0, V1 - V0                                          # local x = u - U0, y = v - V0
ux = lambda u: round(u - U0, 3); vy = lambda v: round(v - V0, 3)
parts = [{"box": {"name": "floor", "min": [0, 0, 0], "max": [X, Y, 0.15]}}]
# eave walls (the u ends, along y)
parts += [{"wall": {"name": "wall_ulo", "from": [0, 0], "to": [0, Y], "z": [0.15, EAVE], "t": 0.3}},
          {"wall": {"name": "wall_uhi", "from": [X, 0], "to": [X, Y], "z": [0.15, EAVE], "t": 0.3}}]
# long walls up to the eave, with the openings
parts.append({"wall": {"name": "wall_vhi", "from": [0, Y], "to": [X, Y], "z": [0.15, EAVE], "t": 0.3,
                       "openings": [{"at": ux(-8.8), "w": 4.5, "h": 4.5}, {"at": ux(-1.6), "w": 1.0, "h": 2.2},
                                    {"at": ux(4.0), "w": 4.5, "h": 4.5}]}})
parts.append({"wall": {"name": "wall_vlo", "from": [0, 0], "to": [X, 0], "z": [0.15, EAVE], "t": 0.3,
                       "openings": [{"at": ux(-1.0), "w": 2.0, "h": 2.4}]}})
# gable infill above the eave on both long faces: 4 stepped boxes per side of the ridge
for face, y in (("vlo", 0.0), ("vhi", Y)):
    for k in range(4):
        z0 = EAVE + k * (RIDGE - EAVE) / 4; z1 = z0 + (RIDGE - EAVE) / 4
        half = X / 2 * (1 - (k + 0.5) / 4)
        parts.append({"box": {"name": f"gable_{face}_{k}", "min": [X / 2 - half, y - 0.15, z0], "max": [X / 2 + half, y + 0.15, z1]}})
# roof: two sloped slabs meeting at the ridge (u = 0 -> x = -U0)
xr = -U0
for side, (xa, xb) in (("lo", (0, xr)), ("hi", (X, xr))):
    parts.append({"beam": {"name": f"roof_{side}", "from": [xa, Y / 2, EAVE], "to": [xb, Y / 2, RIDGE], "t": 0.2, "t2": Y + 0.6, "mat": "metal_ribbed"}})
# canopy over the +v face
parts.append({"box": {"name": "canopy", "min": [ux(-12.6), Y, 4.9], "max": [ux(12.4), Y + 1.6, 5.1], "mat": "steel"}})
for u in (-12.3, 0.0, 12.1):
    parts.append({"box": {"name": f"canopy_post_{u}", "min": [ux(u) - 0.1, Y + 1.4, 0.15], "max": [ux(u) + 0.1, Y + 1.6, 4.9], "mat": "steel"}})
# walled equipment yard off the -u end
yd = [(-26.0, 5.0), (-20.5, 5.0), (-20.5, 16.0), (-26.0, 16.0)]
for k in range(3):                                               # three walls; the fourth is the building
    a, b = [(ux(yd[i][0]), vy(yd[i][1])) for i in ((3, 0), (0, 1), (2, 3))[k]]
    parts.append({"wall": {"name": f"yard_wall{k}", "from": list(a), "to": list(b), "z": [0.0, 1.8], "t": 0.2,
                           "openings": [{"at": 2.0, "w": 1.2, "h": 1.8}] if k == 0 else []}})
c = np.array([159.94, -499.27]); th = np.radians(47.7)
o = c + np.array([U0 * np.cos(th) - V0 * np.sin(th), U0 * np.sin(th) + V0 * np.cos(th)])
spec = {"id": "B06", "name": "warehouse_south", "semantic": "building", "default_mat": "stucco", "origin": [round(float(o[0]), 3), round(float(o[1]), 3), 62.77],
        "yaw_deg": 47.7, "parts": parts,
        "lights": [{"rect": [1, 1, X - 1, Y - 1], "ceiling": EAVE, "spacing": 8, "intensity": 45000.0}]}   # tall, open hall
out = R / "b06/B06_spec.yaml"
out.write_text("# generated by gen_warehouse.py -- edit that, not this\n" + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=200))
print(f"{len(parts)} parts -> {out}")
