"""Add link-preview metadata to the version-root redirect stub.

With ``docs_dir: .`` the site's version root (e.g. ``/0.20/``) is a bare
redirect page generated by mkdocs-redirects (``index.md`` -> ``docs/index.md``)
titled "Redirecting...". Link-preview scrapers (Slack, WhatsApp, iMessage, ...)
read that page's raw HTML and neither run JavaScript nor follow meta-refresh,
so a shared version-root URL previews as just "Redirecting...".

This hook rewrites the generated ``<site_dir>/index.html`` after the build:
a real title plus the same Open Graph / Twitter Card block the theme override
(docs/overrides/main.html) puts on regular pages. MkDocs runs hooks after
plugins for each event, so the redirect stub already exists on_post_build.
"""

import logging
import os
import re

log = logging.getLogger("mkdocs.hooks.social_meta_redirect_stub")

TITLE = "AirStack Documentation"
DESCRIPTION = (
    "An open-source ROS 2 autonomy stack for aerial robots — simulation, "
    "ground control, and layered onboard autonomy that launch as one system. "
    "By the AirLab at Carnegie Mellon University."
)
# The moving /main/ alias keeps this absolute URL valid across releases
# (mike copies real asset files into alias directories).
IMAGE = "https://docs.theairlab.org/main/docs/assets/media/splash-poster.jpg"

META_BLOCK = f"""\
    <meta name="description" content="{DESCRIPTION}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{TITLE}">
    <meta property="og:description" content="{DESCRIPTION}">
    <meta property="og:image" content="{IMAGE}">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="1600">
    <meta property="og:image:height" content="900">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{TITLE}">
    <meta name="twitter:description" content="{DESCRIPTION}">
    <meta name="twitter:image" content="{IMAGE}">
"""


def on_post_build(config, **kwargs):
    index_path = os.path.join(config["site_dir"], "index.html")
    if not os.path.isfile(index_path):
        log.warning("site index.html not found; skipping social meta injection")
        return
    with open(index_path, encoding="utf-8") as f:
        html = f.read()
    if "Redirecting" not in html:
        # Not the redirect stub this hook expects (e.g. the root became a
        # real page) — leave it alone.
        log.info("site index.html is not a redirect stub; skipping")
        return
    html, n_title = re.subn(
        r"<title>[^<]*</title>", f"<title>{TITLE}</title>", html, count=1
    )
    html, n_head = re.subn(
        r"</head>", META_BLOCK + "</head>", html, count=1, flags=re.IGNORECASE
    )
    if not (n_title and n_head):
        log.warning(
            "could not inject social meta into redirect stub "
            "(title replaced: %d, head found: %d)", n_title, n_head
        )
        return
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(html)
    log.info("injected social meta into version-root redirect stub")
