Common:
  # Some configurations are shared across multiple modules in Odometry, so I write them here.
  device: &device cuda

Odometry:
  name: MACVO_Airstack_TRT
  args:
    # Device directive to the VO system
    # NOTE: the system may not follow this device config strictly since some module
    # e.g. those rely on PWC-Net, only support running on cuda device.
    device: *device
    edgewidth: 8
    num_point: 200 # Upper bound of KPs in each frame

    # Match covariance for keypoint on first observation (sub-pixel uncertainty
    # caused by the quantized pixel)
    match_cov_default: 0.25

    # Profiling the system using torch, generate chrome json trace file.
    profile: false

    # Mapping mode provides the dense mapping
    mapping: 5000

    # Online mode does not keep accumulated data inside the VO module.
    online: true

  cov:
    obs:
      type: MatchCovariance
      args:
        device: *device
        match_cov_default: 0.25
        min_depth_cov: 0.05
        min_flow_cov: 0.25

  keypoint:
    type: CovAwareSelector_NoDepth
    args:
      device: *device
      kernel_size: 7
      mask_width: 8
      max_match_cov: 100.0

  mappoint:
    # Mapping feature can be conveniently turn off by using 
    # "type: NoKeypointSelector" instead of the config below.
    type: MappingPointSelector
    args:
      device: *device
      max_depth: 5.0
      max_depth_cov: 0.003
      mask_width: 8

  frontend:
    # type: TRT_FlowFormerCovFrontend
    type: CUDAGraph_FlowFormerCovFrontend
    args:
      device: *device
      weight: /model_weights/MACVO_FrontendCov.pth
      dtype: fp32
      max_flow: -1
      enforce_positive_disparity: false
      decoder_depth: 4

  motion:
    type: StaticMotionModel
    args:

  outlier:
    type: CovarianceSanityFilter
    args:
  
  postprocess:
    type: MotionInterpolate
    args:
  
  keyframe:
    type: AllKeyframe
    args:
  
  optimizer:
    type: Local_TwoFrame_PGO
    args:
      device: cpu
      vectorize: true
      autodiff: false
      parallel: true
      graph_type: disp
