# Any line that does not start with a / will be automatically prefixed using the 
# namespace of the bag_record_pid node.
# mcap_qos is the filename of the MCAP QoS profile. The actual directory will be prefixed by the
# bag_record_pid node via a user specified argument. All MCAP QoS files must be in the same directory.
# The -o or --output argument should not be specified here.
# The -s mcap option will be added automatically.
sections:
  airstack:
    mcap_qos: mcap_qos.yaml
    args: 
      - -b
      - 4000000000 # ~4GB
      - --max-cache-size 
      - 1073741824 # 1GB
    exclude:
      - sensors/*
      - control/*
  control:
    mcap_qos: mcap_qos.yaml
    args: 
      - -b
      - 4000000000 # ~4GB
      - --max-cache-size 
      - 1073741824 # 1GB
    topics:
      - control/vx_pid_info
      - control/vy_pid_info
      - control/vz_pid_info
      - control/x_pid_info
      - control/y_pid_info
      - control/z_pid_info
      - odometry_conversion/odometry
      - trajectory_controller/tracking_point
      - fixed_trajectory_generator/fixed_trajectory_command
  zed:
    mcap_qos: mcap_qos.yaml
    args: 
      - -b
      - 4000000000 # ~4GB
      - --max-cache-size 
      - 1073741824 # 1GB
    topics:
      - sensors/front_stereo/left/image_rect_color
      - sensors/front_stereo/right/image_rect_color
      - sensors/front_stereo/left/camera_info
      - sensors/front_stereo/right/camera_info
      - sensors/front_stereo/pose
      - sensors/front_stereo/disparity/disparity_image
      - sensors/front_stereo/confidence/confidence_map