name: onboard_offboard_bridge
topics:
  # ============= Outgoing ================
  odometry_conversion/odometry:
    type: nav_msgs/msg/Odometry
    from_domain: $(env ROS_DOMAIN_ID)
    to_domain: $(var gcs_domain)


  behavior/behavior_tree_commands:
    type: behavior_tree_msgs/msg/BehaviorTreeCommands
    from_domain: $(env ROS_DOMAIN_ID)
    to_domain: $(var gcs_domain)

  bag_record/bag_recording_status:
    type: std_msgs/msg/Bool
    from_domain: $(var gcs_domain)
    to_domain: $(env ROS_DOMAIN_ID)

  # ============= Incoming ================
  fixed_trajectory_generator/fixed_trajectory_command:
    type: airstack_msgs/msg/FixedTrajectory
    from_domain: $(var gcs_domain)
    to_domain: $(env ROS_DOMAIN_ID)

  bag_record/set_recording_status:
    type: std_msgs/msg/Bool
    from_domain: $(var gcs_domain)
    to_domain: $(env ROS_DOMAIN_ID)