# Base image with ROS2 Humble
# Base image with ROS2 Humble
FROM ros:humble

ARG ROS_WS_DIR

# Set working directory
WORKDIR ${ROS_WS_DIR}

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    ros-humble-ros2cli \
    python3-pip \
    libglib2.0-dev && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Python dependencies
RUN pip3 install --upgrade pip \
    && pip3 install setuptools==57.5.0 pytak pyyaml \
    && pip3 install paho-mqtt

# Copy the local 'ros2tak_tools' directory into the container
COPY /ros_ws/src/ros2tak_tools ${ROS_WS_DIR}/src/ros2tak_tools

# Build the ROS2 workspace
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
                  colcon build --symlink-install"


