# Base image with Python 3
FROM python:3.10-slim

ARG ROS_WS_DIR

# Set working directory
WORKDIR ${ROS_WS_DIR}

# Install necessary dependencies
# Install necessary dependencies
RUN pip install --no-cache-dir asyncio pytak pyyaml cryptography paho-mqtt

