# Count all instances of a specified object class within an area.
# Completes after full coverage of count_area.

# Goal
string object_class
geometry_msgs/Polygon count_area
float32 min_altitude_agl
float32 max_altitude_agl
float32 min_flight_speed
float32 max_flight_speed
---
# Result
bool success
string message
int32 count
geometry_msgs/PoseArray object_poses
---
# Feedback
string status
float32 progress
int32 current_count
geometry_msgs/Point current_position
