"""Canonical RRM types. See docs/architecture.md §3.

Every payload crossing a component boundary is defined here."""

from __future__ import annotations

import math
from enum import Enum
from pathlib import Path
from typing import Any, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field, model_validator

# ---------------------------------------------------------------------------
# Schema  (docs/architecture.md §3)
# ---------------------------------------------------------------------------

ObjectID = str

# "$0", "$1" bind to AbstractAction.targets by index. "*" is a wildcard object.
SELF = "$self"
WILDCARD = "*"


class Verb(str, Enum):
    LOCATE = "LOCATE"
    TAKEOFF = "TAKEOFF"
    LAND = "LAND"
    EXPLORE = "EXPLORE"
    NAVIGATE_TO = "NAVIGATE_TO"
    GRASP = "GRASP"
    RELEASE = "RELEASE"
    PLACE = "PLACE"
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    INSPECT = "INSPECT"
    WAIT = "WAIT"
    ABORT = "ABORT"


class Provenance(str, Enum):
    """Where a fact came from. Never let asserted state pass as observed state."""

    SIM_GROUND_TRUTH = "sim_ground_truth"
    DETECTOR = "detector"
    INFERRED = "inferred"
    ASSERTED_BY_REASONER = "asserted_by_reasoner"


class Predicate(BaseModel):
    """A ground fact. `obj` may be an ObjectID, a literal, or WILDCARD."""

    name: str
    subject: ObjectID
    obj: ObjectID | float | str | None = None
    negated: bool = False

    def __str__(self) -> str:
        arg = "" if self.obj is None else f", {self.obj}"
        return f"{'¬' if self.negated else ''}{self.name}({self.subject}{arg})"


class VerbSpec(BaseModel):
    """Static semantics for a verb. Authored by us, never generated by a model."""

    verb: Verb
    arity: int
    preconditions: list[Predicate] = Field(default_factory=list)
    expected_effects: list[Predicate] = Field(default_factory=list)
    required_resources: frozenset[str] = Field(default_factory=frozenset)


class WorldObject(BaseModel):
    id: ObjectID
    cls: str
    pose: tuple[float, float, float] | None = None
    properties: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, allow_inf_nan=False)
    observed_t: int | None = Field(default=None, ge=0)
    observed_by: Provenance = Provenance.SIM_GROUND_TRUTH


class Relation(BaseModel):
    subject: ObjectID
    predicate: Literal["on", "in", "near", "held_by", "occludes", "supports", "blocked_by"]
    obj: ObjectID
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, allow_inf_nan=False)
    observed_t: int | None = Field(default=None, ge=0)


class RobotState(BaseModel):
    embodiment_id: str = "mock_arm"
    base_pose: tuple[float, float, float] = (0.0, 0.0, 0.0)
    gripper: Literal["open", "closed", "holding"] = "open"
    holding: ObjectID | None = None
    reach: float = 1.5


class WorldState(BaseModel):
    t: int = 0
    objects: list[WorldObject] = Field(default_factory=list)
    relations: list[Relation] = Field(default_factory=list)
    # False means an absent relation is unobserved, not known false. Producers may
    # set this only when the snapshot exhaustively covers the represented objects.
    relations_complete: bool = False
    # Tick at which the producer established exhaustive relation coverage. This
    # also binds negative evidence when the relation list is empty.
    relations_observed_t: int | None = Field(default=None, ge=0)
    robot: RobotState = Field(default_factory=RobotState)
    uncertainty: float = Field(default=0.0, ge=0.0, le=1.0, allow_inf_nan=False)
    uncertainty_provenance: Literal[
        "unbound", "object_evidence_v1", "world_evidence_v2"
    ] = "unbound"

    def get(self, oid: ObjectID) -> WorldObject | None:
        return next((o for o in self.objects if o.id == oid), None)

    def has_relation(self, subject: ObjectID, predicate: str, obj: ObjectID) -> bool:
        return any(
            r.subject == subject and r.predicate == predicate and (obj == WILDCARD or r.obj == obj)
            for r in self.relations
        )


class AbstractAction(BaseModel):
    """Instantiated by the planner. Effects come from the verb table, not the model."""

    id: str
    verb: Verb
    targets: list[ObjectID] = Field(default_factory=list)
    params: dict[str, Any] = Field(default_factory=dict)
    rationale: str = ""

    def __str__(self) -> str:
        return f"{self.verb.value}({', '.join(self.targets)})"


class TaskGraph(BaseModel):
    mission_id: str
    mission_text: str
    nodes: list[AbstractAction]
    version: int = 0


class Violation(BaseModel):
    check: str
    severity: Literal["hard", "soft"]
    detail: str


class SafetyVerdict(BaseModel):
    action_id: str
    verdict: Literal["PASS", "FAIL"]
    violations: list[Violation] = Field(default_factory=list)
    checked: list[str] = Field(default_factory=list)


class Divergence(BaseModel):
    action_id: str
    plan_version: int = Field(ge=0)
    unmet: list[Predicate] = Field(default_factory=list)      # expected ∧ ¬observed
    surprise: list[Predicate] = Field(default_factory=list)    # observed ∧ ¬expected
    magnitude: float = 0.0


class Trajectory(BaseModel):
    """Numeric output of the action policy. The only place coordinates appear."""

    model_config = ConfigDict(frozen=True)

    action_id: str
    kind: Literal["cartesian_position", "joint_position"]
    frame: str
    position_unit: Literal["m", "rad"]
    velocity_unit: Literal["m/s", "rad/s"]
    axes: tuple[str, ...]
    waypoints: list[tuple[float, ...]]
    max_velocity: float
    terminal: bool = False      # last chunk the policy will emit for this subtask

    @model_validator(mode="after")
    def validate_shape(self) -> "Trajectory":
        if not self.action_id or not self.frame or not self.axes or len(set(self.axes)) != len(self.axes):
            raise ValueError("trajectory identity, frame, and unique axes are required")
        if self.kind == "cartesian_position" and self.axes != ("x", "y", "z"):
            raise ValueError("Cartesian trajectories require x/y/z axes")
        if (self.position_unit, self.velocity_unit) != (
                ("m", "m/s") if self.kind == "cartesian_position" else ("rad", "rad/s")):
            raise ValueError("trajectory units do not match coordinate kind")
        if not self.waypoints or any(len(wp) != len(self.axes) for wp in self.waypoints):
            raise ValueError("trajectory waypoint dimensions must match axes")
        if not math.isfinite(self.max_velocity) or self.max_velocity < 0:
            raise ValueError("trajectory velocity must be finite and nonnegative")
        if any(not math.isfinite(value) for wp in self.waypoints for value in wp):
            raise ValueError("trajectory coordinates must be finite")
        return self


class AxisLimit(BaseModel):
    model_config = ConfigDict(frozen=True)
    axis: str
    minimum: float
    maximum: float

    @model_validator(mode="after")
    def validate_bounds(self) -> "AxisLimit":
        if not self.axis or not math.isfinite(self.minimum) or not math.isfinite(self.maximum) \
                or self.minimum >= self.maximum:
            raise ValueError("axis limits must be named, finite, and ordered")
        return self


class NumericLimitProfile(BaseModel):
    """Adapter-authored numeric envelope; units follow the coordinate kind."""

    model_config = ConfigDict(frozen=True)
    ref: str
    embodiment_id: str
    kind: Literal["cartesian_position", "joint_position"]
    frame: str
    position_unit: Literal["m", "rad"]
    velocity_unit: Literal["m/s", "rad/s"]
    axes: tuple[AxisLimit, ...]
    max_velocity: float

    @model_validator(mode="after")
    def validate_profile(self) -> "NumericLimitProfile":
        names = tuple(axis.axis for axis in self.axes)
        if not self.ref or not self.embodiment_id or not self.frame or not names \
                or len(set(names)) != len(names):
            raise ValueError("numeric profile requires identity, frame, and unique axes")
        if self.kind == "cartesian_position" and names != ("x", "y", "z"):
            raise ValueError("Cartesian profile requires x/y/z axes")
        if (self.position_unit, self.velocity_unit) != (
                ("m", "m/s") if self.kind == "cartesian_position" else ("rad", "rad/s")):
            raise ValueError("numeric profile units do not match coordinate kind")
        if not math.isfinite(self.max_velocity) or self.max_velocity <= 0:
            raise ValueError("numeric profile velocity must be finite and positive")
        return self


class Termination(str, Enum):
    """Why the inner execution loop stopped."""

    COMPLETE = "COMPLETE"       # expected effects satisfied — the success path
    TIMEOUT = "TIMEOUT"         # cycle budget spent, effects still unmet
    UNSAFE = "UNSAFE"           # numeric safety rejected a trajectory
    UNCERTAIN = "UNCERTAIN"     # world evidence exceeded autonomous admission
    STALE_CONTEXT = "STALE_CONTEXT"  # task or plan changed after its recorded revision
    INTERRUPTED = "INTERRUPTED"  # stop latched; safe physical state is separate evidence


class RunMetrics(BaseModel):
    """Per-episode measurements. Names match docs/benchmarks.md §3."""

    task_id: str = ""
    task_success: bool = False
    aborted: bool = False
    replans: int = 0
    action_count: int = 0
    inner_cycles: int = 0
    divergences: int = 0
    recoveries: int = 0
    safety_rejections: int = 0
    planning_latency_ms: float = 0.0

    @property
    def recovery_rate(self) -> float | None:
        """Recovered divergences, undefined when no divergence was observed."""
        return self.recoveries / self.divergences if self.divergences else None


class Task(BaseModel):
    """A benchmark task. See docs/benchmarks.md §2."""

    id: str
    revision: str = "core-task-v1"
    mission: str
    goal: Predicate
    world: dict[str, Any] = Field(default_factory=dict)
    expect_abort: bool = False   # T9: correctly reporting failure IS success


# ---------------------------------------------------------------------------
# Substitution boundary  (docs/architecture.md §2.1)
# ---------------------------------------------------------------------------

class WorldBackend(Protocol):
    """The complete surface Isaac Sim must implement. Nothing above it changes.

    `observe()` returns semantic belief, so a real backend is responsible for the
    perception step: sensors -> WorldState. In Phases 3-5 that is a ground-truth shim
    reading poses straight from the simulator.
    """

    def observe(self) -> WorldState:
        """Current semantic belief. Must be a copy — callers retain snapshots."""
        ...

    def apply(self, action: AbstractAction, traj: Trajectory) -> None:
        """Execute one trajectory chunk and advance time."""
        ...

    def begin_dispatch(self, action: AbstractAction, dispatch_id: str) -> None:
        """Signal a new outer-loop attempt at this action."""
        ...

    def end_dispatch(self, dispatch_id: str) -> None:
        """Release a completed, failed or interrupted attempt."""
        ...

    def cancel_dispatch(self, dispatch_id: str, generation: int) -> bool:
        """Acknowledge cancellation; acknowledgement is not safe-state proof."""
        ...

    def observe_safe_state(self, dispatch_id: str, generation: int):
        """Return independent adapter safe-state evidence, or None."""
        ...


class ActionPolicy(Protocol):
    """The surface GR00T must implement, behind the embodiment adapter."""

    def step(self, action: AbstractAction, ws: WorldState) -> Trajectory:
        ...

    def reset(self, action_id: str) -> None:
        ...
