"""Canonical RRM types. See docs/architecture.md §3.

Every payload crossing a component boundary is defined here."""

from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Any, Literal, Protocol

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Schema  (docs/architecture.md §3)
# ---------------------------------------------------------------------------

ObjectID = str

# "$0", "$1" bind to AbstractAction.targets by index. "*" is a wildcard object.
SELF = "$self"
WILDCARD = "*"


class Verb(str, Enum):
    LOCATE = "LOCATE"
    TAKEOFF = "TAKEOFF"
    LAND = "LAND"
    EXPLORE = "EXPLORE"
    NAVIGATE_TO = "NAVIGATE_TO"
    GRASP = "GRASP"
    RELEASE = "RELEASE"
    PLACE = "PLACE"
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    INSPECT = "INSPECT"
    WAIT = "WAIT"
    ABORT = "ABORT"


class Provenance(str, Enum):
    """Where a fact came from. Never let asserted state pass as observed state."""

    SIM_GROUND_TRUTH = "sim_ground_truth"
    DETECTOR = "detector"
    INFERRED = "inferred"
    ASSERTED_BY_REASONER = "asserted_by_reasoner"


class Predicate(BaseModel):
    """A ground fact. `obj` may be an ObjectID, a literal, or WILDCARD."""

    name: str
    subject: ObjectID
    obj: ObjectID | float | str | None = None
    negated: bool = False

    def __str__(self) -> str:
        arg = "" if self.obj is None else f", {self.obj}"
        return f"{'¬' if self.negated else ''}{self.name}({self.subject}{arg})"


class VerbSpec(BaseModel):
    """Static semantics for a verb. Authored by us, never generated by a model."""

    verb: Verb
    arity: int
    preconditions: list[Predicate] = Field(default_factory=list)
    expected_effects: list[Predicate] = Field(default_factory=list)


class WorldObject(BaseModel):
    id: ObjectID
    cls: str
    pose: tuple[float, float, float] | None = None
    properties: dict[str, Any] = Field(default_factory=dict)
    confidence: float = 1.0
    observed_by: Provenance = Provenance.SIM_GROUND_TRUTH


class Relation(BaseModel):
    subject: ObjectID
    predicate: Literal["on", "in", "near", "held_by", "occludes", "supports", "blocked_by"]
    obj: ObjectID
    confidence: float = 1.0


class RobotState(BaseModel):
    embodiment_id: str = "mock_arm"
    base_pose: tuple[float, float, float] = (0.0, 0.0, 0.0)
    gripper: Literal["open", "closed", "holding"] = "open"
    holding: ObjectID | None = None
    reach: float = 1.5


class WorldState(BaseModel):
    t: int = 0
    objects: list[WorldObject] = Field(default_factory=list)
    relations: list[Relation] = Field(default_factory=list)
    robot: RobotState = Field(default_factory=RobotState)
    uncertainty: float = 0.0

    def get(self, oid: ObjectID) -> WorldObject | None:
        return next((o for o in self.objects if o.id == oid), None)

    def has_relation(self, subject: ObjectID, predicate: str, obj: ObjectID) -> bool:
        return any(
            r.subject == subject and r.predicate == predicate and (obj == WILDCARD or r.obj == obj)
            for r in self.relations
        )


class AbstractAction(BaseModel):
    """Instantiated by the planner. Effects come from the verb table, not the model."""

    id: str
    verb: Verb
    targets: list[ObjectID] = Field(default_factory=list)
    params: dict[str, Any] = Field(default_factory=dict)
    rationale: str = ""

    def __str__(self) -> str:
        return f"{self.verb.value}({', '.join(self.targets)})"


class TaskGraph(BaseModel):
    mission_id: str
    mission_text: str
    nodes: list[AbstractAction]
    version: int = 0


class Violation(BaseModel):
    check: str
    severity: Literal["hard", "soft"]
    detail: str


class SafetyVerdict(BaseModel):
    action_id: str
    verdict: Literal["PASS", "FAIL"]
    violations: list[Violation] = Field(default_factory=list)
    checked: list[str] = Field(default_factory=list)


class Divergence(BaseModel):
    action_id: str
    unmet: list[Predicate] = Field(default_factory=list)      # expected ∧ ¬observed
    surprise: list[Predicate] = Field(default_factory=list)    # observed ∧ ¬expected
    magnitude: float = 0.0


class Trajectory(BaseModel):
    """Numeric output of the action policy. The only place coordinates appear."""

    action_id: str
    waypoints: list[tuple[float, ...]]
    max_velocity: float
    terminal: bool = False      # last chunk the policy will emit for this subtask


class Termination(str, Enum):
    """Why the inner execution loop stopped."""

    COMPLETE = "COMPLETE"       # expected effects satisfied — the success path
    TIMEOUT = "TIMEOUT"         # cycle budget spent, effects still unmet
    UNSAFE = "UNSAFE"           # numeric safety rejected a trajectory


class RunMetrics(BaseModel):
    """Per-episode measurements. Names match docs/benchmarks.md §3."""

    task_id: str = ""
    task_success: bool = False
    aborted: bool = False
    replans: int = 0
    action_count: int = 0
    inner_cycles: int = 0
    divergences: int = 0
    recoveries: int = 0
    unsafe_actions: int = 0
    planning_latency_ms: float = 0.0

    @property
    def recovery_rate(self) -> float:
        return self.recoveries / self.divergences if self.divergences else 1.0


class Task(BaseModel):
    """A benchmark task. See docs/benchmarks.md §2."""

    id: str
    mission: str
    goal: Predicate
    world: dict[str, Any] = Field(default_factory=dict)
    expect_abort: bool = False   # T9: correctly reporting failure IS success


# ---------------------------------------------------------------------------
# Substitution boundary  (docs/architecture.md §2.1)
# ---------------------------------------------------------------------------

class WorldBackend(Protocol):
    """The complete surface Isaac Sim must implement. Nothing above it changes.

    `observe()` returns semantic belief, so a real backend is responsible for the
    perception step: sensors -> WorldState. In Phases 3-5 that is a ground-truth shim
    reading poses straight from the simulator.
    """

    def observe(self) -> WorldState:
        """Current semantic belief. Must be a copy — callers retain snapshots."""
        ...

    def apply(self, action: AbstractAction, traj: Trajectory) -> None:
        """Execute one trajectory chunk and advance time."""
        ...

    def begin_dispatch(self, action: AbstractAction) -> None:
        """Signal a new outer-loop attempt at this action."""
        ...


class ActionPolicy(Protocol):
    """The surface GR00T must implement, behind the embodiment adapter."""

    def step(self, action: AbstractAction, ws: WorldState) -> Trajectory:
        ...

    def reset(self, action_id: str) -> None:
        ...
