"""Verb table and predicate evaluation. See docs/architecture.md §3.2.

Preconditions and effects are authored here, never generated by a model."""

from __future__ import annotations

from typing import Any

from .contracts import Truth
from .schema import (
    AbstractAction, Predicate, SELF, Verb, VerbSpec, WILDCARD, WorldState,
)

# ---------------------------------------------------------------------------
# Verb table  (docs/architecture.md §3.2)
# ---------------------------------------------------------------------------

def _p(name: str, subject: str, obj: Any = None, negated: bool = False) -> Predicate:
    return Predicate(name=name, subject=subject, obj=obj, negated=negated)


VERB_TABLE: dict[Verb, VerbSpec] = {
    Verb.LOCATE: VerbSpec(
        verb=Verb.LOCATE,
        arity=1,
        preconditions=[_p("exists", "$0")],
        expected_effects=[_p("localized", "$0")],
        required_resources=frozenset({"perception"}),
    ),
    Verb.TAKEOFF: VerbSpec(
        verb=Verb.TAKEOFF,
        arity=0,
        expected_effects=[_p("airborne", SELF)],
        required_resources=frozenset({"mobility"}),
    ),
    Verb.LAND: VerbSpec(
        verb=Verb.LAND,
        arity=0,
        expected_effects=[_p("grounded", SELF)],
        required_resources=frozenset({"mobility"}),
    ),
    Verb.EXPLORE: VerbSpec(
        verb=Verb.EXPLORE,
        arity=0,
        expected_effects=[_p("area_explored", SELF)],
        required_resources=frozenset({"mobility", "perception"}),
    ),
    Verb.NAVIGATE_TO: VerbSpec(
        verb=Verb.NAVIGATE_TO,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("localized", "$0")],
        expected_effects=[_p("near", SELF, "$0")],
        required_resources=frozenset({"mobility"}),
    ),
    Verb.GRASP: VerbSpec(
        verb=Verb.GRASP,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("graspable", "$0"), _p("reachable", "$0"),
                       _p("gripper_empty", SELF)],
        expected_effects=[_p("holding", SELF, "$0"), _p("on", "$0", WILDCARD, negated=True)],
        required_resources=frozenset({"manipulation"}),
    ),
    Verb.RELEASE: VerbSpec(
        verb=Verb.RELEASE,
        arity=1,
        preconditions=[_p("holding", SELF, "$0")],
        expected_effects=[_p("gripper_empty", SELF)],
        required_resources=frozenset({"manipulation"}),
    ),
    Verb.PLACE: VerbSpec(
        verb=Verb.PLACE,
        arity=2,
        preconditions=[_p("holding", SELF, "$0"), _p("exists", "$1"), _p("reachable", "$1")],
        expected_effects=[_p("on", "$0", "$1"), _p("gripper_empty", SELF)],
        required_resources=frozenset({"manipulation"}),
    ),
    Verb.OPEN: VerbSpec(
        verb=Verb.OPEN,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("reachable", "$0"), _p("open", "$0", negated=True)],
        expected_effects=[_p("open", "$0")],
        required_resources=frozenset({"manipulation"}),
    ),
    Verb.CLOSE: VerbSpec(
        verb=Verb.CLOSE,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("reachable", "$0"), _p("open", "$0")],
        expected_effects=[_p("open", "$0", negated=True)],
        required_resources=frozenset({"manipulation"}),
    ),
    Verb.INSPECT: VerbSpec(
        verb=Verb.INSPECT, arity=1,
        preconditions=[_p("exists", "$0")], expected_effects=[_p("inspected", "$0")],
        required_resources=frozenset({"perception"}),
    ),
    Verb.WAIT: VerbSpec(verb=Verb.WAIT, arity=0),
    Verb.ABORT: VerbSpec(verb=Verb.ABORT, arity=0),
}


def bind(template: Predicate, action: AbstractAction) -> Predicate:
    """Resolve $0/$1/$self placeholders against an action's targets."""

    def resolve(token: Any) -> Any:
        if not isinstance(token, str):
            return token
        if token == SELF:
            return SELF
        if token.startswith("$") and token[1:].isdigit():
            idx = int(token[1:])
            if idx >= len(action.targets):
                raise ValueError(f"{action} has no target ${idx}")
            return action.targets[idx]
        return token

    return Predicate(
        name=template.name,
        subject=resolve(template.subject),
        obj=resolve(template.obj),
        negated=template.negated,
    )


def preconditions_of(action: AbstractAction) -> list[Predicate]:
    return [bind(t, action) for t in VERB_TABLE[action.verb].preconditions]


def expected_effects_of(action: AbstractAction) -> list[Predicate]:
    return [bind(t, action) for t in VERB_TABLE[action.verb].expected_effects]


# ---------------------------------------------------------------------------
# Predicate evaluation against world state
# ---------------------------------------------------------------------------

def predicate_truth(pred: Predicate, ws: WorldState) -> Truth:
    """Evaluate a ground predicate without converting missing evidence to false."""
    truth = _positive_truth(pred, ws)
    return truth.negate() if pred.negated else truth


def holds(pred: Predicate, ws: WorldState) -> bool:
    """Strict compatibility boundary: only explicit truth satisfies a predicate."""
    return predicate_truth(pred, ws) is Truth.TRUE


def _boolean_property(ws: WorldState, subject: str, name: str) -> Truth:
    obj = ws.get(subject)
    if obj is None:
        return Truth.UNKNOWN
    value = obj.properties.get(name)
    if type(value) is not bool:
        return Truth.UNKNOWN
    return Truth.TRUE if value else Truth.FALSE


def _positive_truth(pred: Predicate, ws: WorldState) -> Truth:
    name, subj, obj = pred.name, pred.subject, pred.obj

    if name == "exists":
        return Truth.TRUE if ws.get(subj) is not None else Truth.UNKNOWN
    if name == "gripper_empty":
        if (ws.robot.holding is None) == (ws.robot.gripper != "holding"):
            return Truth.TRUE if ws.robot.holding is None else Truth.FALSE
        return Truth.UNKNOWN
    if name == "holding":
        if (ws.robot.holding is None) != (ws.robot.gripper != "holding"):
            return Truth.UNKNOWN
        if ws.robot.holding is not None and ws.get(ws.robot.holding) is None:
            return Truth.UNKNOWN
        return Truth.TRUE if ws.robot.holding == obj else Truth.FALSE
    if name == "graspable":
        return _boolean_property(ws, subj, "graspable")
    if name == "localized":
        o = ws.get(subj)
        return Truth.TRUE if o is not None and o.pose is not None else Truth.UNKNOWN
    if name == "open":
        return _boolean_property(ws, subj, "open")
    if name == "inspected":
        return _boolean_property(ws, subj, "inspected")
    if name == "reachable":
        o = ws.get(subj)
        if o is None or o.pose is None:
            return Truth.UNKNOWN
        bx, by, _ = ws.robot.base_pose
        ox, oy, _ = o.pose
        reachable = ((ox - bx) ** 2 + (oy - by) ** 2) ** 0.5 <= ws.robot.reach
        return Truth.TRUE if reachable else Truth.FALSE
    if name in ("on", "in", "near"):
        if subj == SELF:
            return Truth.UNKNOWN  # robot-relative spatial facts are not represented
        if ws.get(subj) is None:
            return Truth.UNKNOWN
        if obj not in (None, WILDCARD) and ws.get(str(obj)) is None:
            return Truth.UNKNOWN
        if ws.has_relation(subj, name, str(obj)):
            return Truth.TRUE
        return Truth.FALSE if ws.relations_complete else Truth.UNKNOWN

    return Truth.UNKNOWN
