"""Verb table and predicate evaluation. See docs/architecture.md §3.2.

Preconditions and effects are authored here, never generated by a model."""

from __future__ import annotations

from typing import Any

from .schema import (
    AbstractAction, Predicate, SELF, Verb, VerbSpec, WILDCARD, WorldState,
)

# ---------------------------------------------------------------------------
# Verb table  (docs/architecture.md §3.2)
# ---------------------------------------------------------------------------

def _p(name: str, subject: str, obj: Any = None, negated: bool = False) -> Predicate:
    return Predicate(name=name, subject=subject, obj=obj, negated=negated)


VERB_TABLE: dict[Verb, VerbSpec] = {
    Verb.LOCATE: VerbSpec(
        verb=Verb.LOCATE,
        arity=1,
        preconditions=[_p("exists", "$0")],
        expected_effects=[_p("localized", "$0")],
    ),
    Verb.NAVIGATE_TO: VerbSpec(
        verb=Verb.NAVIGATE_TO,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("localized", "$0")],
        expected_effects=[_p("near", SELF, "$0")],
    ),
    Verb.GRASP: VerbSpec(
        verb=Verb.GRASP,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("graspable", "$0"), _p("reachable", "$0"),
                       _p("gripper_empty", SELF)],
        expected_effects=[_p("holding", SELF, "$0"), _p("on", "$0", WILDCARD, negated=True)],
    ),
    Verb.RELEASE: VerbSpec(
        verb=Verb.RELEASE,
        arity=1,
        preconditions=[_p("holding", SELF, "$0")],
        expected_effects=[_p("gripper_empty", SELF)],
    ),
    Verb.PLACE: VerbSpec(
        verb=Verb.PLACE,
        arity=2,
        preconditions=[_p("holding", SELF, "$0"), _p("exists", "$1"), _p("reachable", "$1")],
        expected_effects=[_p("on", "$0", "$1"), _p("gripper_empty", SELF)],
    ),
    Verb.OPEN: VerbSpec(
        verb=Verb.OPEN,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("reachable", "$0"), _p("open", "$0", negated=True)],
        expected_effects=[_p("open", "$0")],
    ),
    Verb.CLOSE: VerbSpec(
        verb=Verb.CLOSE,
        arity=1,
        preconditions=[_p("exists", "$0"), _p("reachable", "$0"), _p("open", "$0")],
        expected_effects=[_p("open", "$0", negated=True)],
    ),
    Verb.INSPECT: VerbSpec(
        verb=Verb.INSPECT, arity=1,
        preconditions=[_p("exists", "$0")], expected_effects=[_p("inspected", "$0")],
    ),
    Verb.WAIT: VerbSpec(verb=Verb.WAIT, arity=0),
    Verb.ABORT: VerbSpec(verb=Verb.ABORT, arity=0),
}


def bind(template: Predicate, action: AbstractAction) -> Predicate:
    """Resolve $0/$1/$self placeholders against an action's targets."""

    def resolve(token: Any) -> Any:
        if not isinstance(token, str):
            return token
        if token == SELF:
            return SELF
        if token.startswith("$") and token[1:].isdigit():
            idx = int(token[1:])
            if idx >= len(action.targets):
                raise ValueError(f"{action} has no target ${idx}")
            return action.targets[idx]
        return token

    return Predicate(
        name=template.name,
        subject=resolve(template.subject),
        obj=resolve(template.obj),
        negated=template.negated,
    )


def preconditions_of(action: AbstractAction) -> list[Predicate]:
    return [bind(t, action) for t in VERB_TABLE[action.verb].preconditions]


def expected_effects_of(action: AbstractAction) -> list[Predicate]:
    return [bind(t, action) for t in VERB_TABLE[action.verb].expected_effects]


# ---------------------------------------------------------------------------
# Predicate evaluation against world state
# ---------------------------------------------------------------------------

def holds(pred: Predicate, ws: WorldState) -> bool:
    """Evaluate a ground predicate. Unknown is treated as False.

    TODO(phase-4): make this tri-state. Under real perception, "unknown" and
    "false" are different, and collapsing them will understate uncertainty.
    """
    truth = _holds_positive(pred, ws)
    return not truth if pred.negated else truth


def _holds_positive(pred: Predicate, ws: WorldState) -> bool:
    name, subj, obj = pred.name, pred.subject, pred.obj

    if name == "exists":
        return ws.get(subj) is not None
    if name == "gripper_empty":
        return ws.robot.holding is None
    if name == "holding":
        return ws.robot.holding == obj
    if name == "graspable":
        o = ws.get(subj)
        return bool(o and o.properties.get("graspable", False))
    if name == "localized":
        o = ws.get(subj)
        return bool(o and o.pose is not None)
    if name == "open":
        o = ws.get(subj)
        return bool(o and o.properties.get("open", False))
    if name == "inspected":
        o = ws.get(subj)
        return bool(o and o.properties.get("inspected", False))
    if name == "reachable":
        o = ws.get(subj)
        if o is None or o.pose is None:
            return False
        bx, by, _ = ws.robot.base_pose
        ox, oy, _ = o.pose
        return ((ox - bx) ** 2 + (oy - by) ** 2) ** 0.5 <= ws.robot.reach
    if name in ("on", "in", "near"):
        if subj == SELF:
            return False  # robot-relative spatial facts not modelled in the mock
        return ws.has_relation(subj, name, str(obj))

    log.warning("unknown predicate %r evaluated as False", name)
    return False


