# expects context to be the root of the repository, i.e. AirStack/. this is so we can access AirStack/ros_ws/
FROM osrf/ros:humble-desktop-full

WORKDIR /root/AirStack

RUN apt update
# Install dev tools
RUN apt install -y \
    vim nano wget curl tree \
    cmake build-essential \
    less htop jq \
    python3-pip

# Package dependencies
# perform ROS dependency installation for our workspace.