name: onboard_offboard_bridge
topics:
  # Outgoing
  odometry_conversion/odometry:
    type: nav_msgs/msg/Odometry
    from_domain: $(env ROS_DOMAIN_ID)
    to_domain: $(var gcs_domain)


  behavior/behavior_tree_commands:
    type: behavior_tree_msgs/msg/BehaviorTreeCommands
    from_domain: $(env ROS_DOMAIN_ID)
    to_domain: $(var gcs_domain)

  # Incoming
  global_plan:
    type: nav_msgs/msg/Path
    from_domain: $(var gcs_domain)
    to_domain: $(env ROS_DOMAIN_ID)