# Any line that does not start with a / will be automatically prefixed using the 
# namespace of the bag_record_pid node.
# mcap_qos is the filename of the MCAP QoS profile. The actual directory will be prefixed by the
# bag_record_pid node via a user specified argument. All MCAP QoS files must be in the same directory.
# The -o or --output argument should not be specified here.
# The -s mcap option will be added automatically.
sections:
  spot_rgb:
    mcap_qos: mcap_qos.yaml
    args: 
      - -b
      - 4000000000 # ~4GB
      - --max-cache-size 
      - 1073741824 # 1GB
    exclude:
      - /tf
      - /tf_static

# Extra or skipped topics:
# - spot/depth_registered/back/points
# - spot/depth_registered/frontleft/points
# - spot/depth_registered/frontright/points
# - spot/depth_registered/left/points
# - spot/depth_registered/right/point
# - spot/depth_registered/back/camera_info
# - spot/depth_registered/back/image
# - spot/depth_registered/frontleft/camera_info
# - spot/depth_registered/frontleft/image
# - spot/depth_registered/frontright/camera_info
# - spot/depth_registered/frontright/image
# - spot/depth_registered/hand/points
# - spot/depth_registered/hand/camera_info
# - spot/depth_registered/hand/image
# - spot/depth_registered/left/camera_info
# - spot/depth_registered/left/image
# - spot/depth_registered/right/camera_info
# - spot/depth_registered/right/image
# ouster/scan
# spot/camera/back/compressed
# spot/camera/frontleft/compressed
# spot/camera/frontright/compressed
# spot/camera/hand/compressed
# spot/camera/left/compressed
# spot/camera/right/compressed
# spot/depth_registered/image_rect/compressed
# spot/depth_registered/image_rect/compressedDepth
# spot/depth_registered/image_rect/theora