# Message defining constants for the wireless joysticks used by ACL

# buttons
int64 A=0
int64 B=1
int64 X=2
int64 Y=3
int64 LB=4
int64 RB=5
int64 BACK=6
int64 START=7
int64 CENTER=8 # center 'on' button
int64 LS=9 # left joystick
int64 RS=10 # right joystick
int64 LEFT=11
int64 RIGHT=12
int64 UP=13
int64 DOWN=14

# axes
int64 LEFT_X=0
int64 LEFT_Y=1
int64 LT=2
int64 RIGHT_X=3
int64 RIGHT_Y=4
int64 RT=5
