data:
  odom_x: odometry_conversion/odometry.pose.pose.position.x
  odom_y: odometry_conversion/odometry.pose.pose.position.y
  vel_x: odometry_conversion/odometry.twist.twist.linear.x
  vel_y: odometry_conversion/odometry.twist.twist.linear.y
  tp_x: trajectory_controller/tracking_point.pose.position.x
  tp_y: trajectory_controller/tracking_point.pose.position.y
  
  fixed_traj: fixed_trajectory_generator/fixed_trajectory_command.type
  
  xpid: control/x_pid_info
  ypid: control/y_pid_info
  zpid: control/z_pid_info
  vxpid: control/vx_pid_info
  vypid: control/vy_pid_info
  vzpid: control/vz_pid_info
  
rcparams:
  font.size: 14
  axes.titlesize: 20
  axes.labelsize: 16
  xtick.labelsize: 14
  ytick.labelsize: 14
  legend.fontsize: 16
  figure.titlesize: 24

profiles:
  fixed_traj_split:
    split:
      field: fixed_traj
      condition: x != None
      as: axes
      #keep_indices: 1, 2
  test:
    set_aspect: aspect_type
  pid:
    suptitle: title
    axes:
        - col: 1
          plots:
          - x: pid.header_time - pid.header_time[0]
            y: pid.measured
            fmt: .-
            label: Measured
          - x: pid.header_time - pid.header_time[0]
            y: pid.target
            fmt: .-
            label: Target
        - col: 2
          plots:
          - x: pid.header_time - pid.header_time[0]
            y: pid.p_component
            fmt: .-
            label: p
          - x: pid.header_time - pid.header_time[0]
            y: pid.i_component
            fmt: .-
            label: i
          - x: pid.header_time - pid.header_time[0]
            y: pid.d_component
            fmt: .-
            label: d
          - x: pid.header_time - pid.header_time[0]
            y: pid.ff_component
            fmt: .-
            label: ff
          - x: pid.header_time - pid.header_time[0]
            y: pid.control
            fmt: .-
            label: control

figures:
  - profiles: fixed_traj_split
    suptitle: "'Tracking, max velocity: %0.2f m/s' % max(np.sqrt(vel_x**2 + vel_y**2))"
    axes:
      - profiles: test(aspect_type='equal')
        plots:
          - x: odom_x
            y: odom_y
            fmt: .-
            label: Robot Position
          - x: tp_x
            y: tp_y
            fmt: .-
            label: Tracking Point
  - profiles: fixed_traj_split, pid(title='X', pid=xpid)
  - profiles: fixed_traj_split, pid(title='Y', pid=ypid)
  - profiles: fixed_traj_split, pid(title='Z', pid=zpid)
  - profiles: fixed_traj_split, pid(title='VX', pid=vxpid)
  - profiles: fixed_traj_split, pid(title='VY', pid=vypid)
  - profiles: fixed_traj_split, pid(title='VZ', pid=vzpid)
