"""import_megascans.py — turn a Megascans/glTF surface zip into a bound material.

    python3 tools/import_megascans.py ~/Downloads/road_asphalt_*.zip
    python3 tools/import_megascans.py --all        # everything in ~/Downloads

WHAT THESE PACKS ARE
--------------------
A Megascans "ue" surface zip is a glTF asset plus a Textures/ folder, and the
textures are ordinary PNG/JPG:

    T_<id>_<res>_B.png     base colour
    T_<id>_<res>_N.png     normal
    T_<id>_<res>_ORM.png   occlusion / roughness / metallic, packed R/G/B
    T_<id>_<res>_H.png     height (optional)

The glTF geometry is a display plane and is not wanted — only the maps are.
OmniPBR reads all of them directly, including the packed ORM via
`enable_ORM_texture`, so nothing needs converting or channel-splitting.

WHY A .usda WRAPPER
-------------------
Same reason `Grass_Cut.usda` exists: a material has to BE a
`UsdShade.Material` to be bindable, and the asset pack references materials by
USD path. This writes one wrapper per surface with the texture paths anchored
relative to the layer, so the result is portable between the host and the
container mount.
"""

import argparse
import glob
import os
import re
import shutil
import zipfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_MATS = os.path.join(os.path.dirname(_HERE), "assets", "materials")
_DEST = os.path.join(_MATS, "megascans")

# zip name fragment -> the material name we want to bind by
NAMES = {
    "brick_wall_worn": "Brick_Wall_Worn",
    "burnt_forest_floor": "Burnt_Forest_Floor",
    "damaged_asphalt": "Damaged_Asphalt",
    # Both spellings land on the same material, so a newer pack REPLACES the
    # older one rather than sitting beside it under a generated name.
    "road_asphalt": "Road_Asphalt",
    "asphalt_road": "Road_Asphalt",
    "white_road_line": "Road_Line_White",
    "yellow_road_line": "Road_Line_Yellow",
    "road_marking_line": "Road_Marking_Line",
    "painted_line_dense": "Road_Line_Dense",
    "road_line": "Road_Line",
}

_TEMPLATE = '''#usda 1.0
(
    defaultPrim = "{name}"
)

# Generated by tools/import_megascans.py from {src}
# Textures are Megascans maps; ORM is packed R=occlusion G=roughness B=metallic,
# which OmniPBR unpacks itself when `enable_ORM_texture` is on.

def Material "{name}"
{{
    token outputs:mdl:displacement.connect = </{name}/Shader.outputs:out>
    token outputs:mdl:surface.connect = </{name}/Shader.outputs:out>
    token outputs:mdl:volume.connect = </{name}/Shader.outputs:out>

    def Shader "Shader"
    {{
        uniform token info:implementationSource = "sourceAsset"
        uniform asset info:mdl:sourceAsset = @OmniPBR.mdl@
        uniform token info:mdl:sourceAsset:subIdentifier = "OmniPBR"
{inputs}
        token outputs:out (renderType = "material")
    }}
}}
'''


def _texture(files, suffix):
    for f in files:
        stem = os.path.basename(f)
        if re.search(r"_" + suffix + r"(-O)?\.(png|jpg|jpeg)$", stem, re.I):
            return stem
    return None


def convert(zip_path, verbose=True):
    frag = os.path.basename(zip_path).lower()
    name = None
    for k in sorted(NAMES, key=len, reverse=True):
        if k in frag:
            name = NAMES[k]
            break
    if name is None:
        name = re.sub(r"[^A-Za-z0-9]+", "_", os.path.basename(zip_path))[:40]

    out = os.path.join(_DEST, name)
    # WIPE FIRST. Two packs writing into one material folder leaves two sets
    # of maps, and `_texture()` then picks whichever sorts first — so a
    # "replacement" would silently keep using the old textures.
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out, exist_ok=True)
    with zipfile.ZipFile(zip_path) as z:
        for m in z.namelist():
            if not m.lower().startswith("textures/"):
                continue          # the glTF plane is not wanted
            if not m.lower().endswith((".png", ".jpg", ".jpeg")):
                continue
            with z.open(m) as src, open(
                    os.path.join(out, os.path.basename(m)), "wb") as dst:
                shutil.copyfileobj(src, dst)

    return write_wrapper(name, src=os.path.basename(zip_path), verbose=verbose)


def write_wrapper(name, src="(extracted textures)", verbose=True):
    """Write ``<name>.usda`` for the maps already sitting in ``<name>/``.

    Split out of `convert` because the wrapper is DERIVED from the textures,
    and the two get separated: the maps are committed but the `.usda` is not,
    so a fresh clone has every Megascans texture and no material to bind. USD
    then fails the reference with "Could not open asset ...Road_Asphalt.usda"
    and the surface falls back to flat colour — quietly, mid-scene.
    """
    out = os.path.join(_DEST, name)
    files = sorted(glob.glob(os.path.join(out, "*")))
    if not files:
        return None

    base = _texture(files, "B")
    orm = _texture(files, "ORM")
    nrm = _texture(files, "N")

    lines = []
    if base:
        lines.append('        asset inputs:diffuse_texture = '
                     '@./{0}/{1}@'.format(name, base))
    if nrm:
        lines.append('        asset inputs:normalmap_texture = '
                     '@./{0}/{1}@'.format(name, nrm))
    if orm:
        lines.append('        bool inputs:enable_ORM_texture = 1')
        lines.append('        asset inputs:ORM_texture = '
                     '@./{0}/{1}@'.format(name, orm))
    # TILE SIZE BY ROLE, not one default for everything.
    #
    # A large ground surface repeats visibly: at one tile per 2 m a 250 m
    # plate shows 125 repeats and reads as a grid of rectangles, however
    # seamless the map is. Ground and road get ~9 m tiles; smaller surfaces
    # keep a tighter scale because they are seen closer and cover less.
    #
    # Set here rather than edited afterwards so a re-import cannot silently
    # revert it — which is exactly what happened when the asphalt pack was
    # replaced.
    tile = 0.11 if any(k in name for k in ("Asphalt", "Floor", "Ground")) else 0.35
    lines.append('        float2 inputs:texture_scale = ({0}, {0})'.format(tile))
    lines.append('        bool inputs:project_uvw = 1')
    lines.append('        bool inputs:world_or_object = 1')

    usda = os.path.join(_DEST, name + ".usda")
    with open(usda, "w") as fh:
        fh.write(_TEMPLATE.format(name=name, src=src,
                                  inputs="\n".join(lines)))
    if verbose:
        print("  {0:<22s} base={1} orm={2} normal={3}".format(
            name, bool(base), bool(orm), bool(nrm)))
    return usda


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("zips", nargs="*")
    ap.add_argument("--all", action="store_true",
                    help="every *_ue_*.zip in ~/Downloads")
    ap.add_argument("--rebuild", action="store_true",
                    help="re-write the .usda wrappers from the textures already "
                         "in assets/materials/megascans, no zips needed")
    args = ap.parse_args()

    os.makedirs(_DEST, exist_ok=True)

    if args.rebuild:
        # The textures are committed; the wrappers are generated, so a clone
        # has the maps and no material. This puts them back without needing
        # the original packs.
        names = sorted(d for d in os.listdir(_DEST)
                       if os.path.isdir(os.path.join(_DEST, d)))
        for n in names:
            write_wrapper(n)
        print(f"[import_megascans] rebuilt {len(names)} wrapper(s) in {_DEST}")
        return 0

    zips = list(args.zips)
    if args.all or not zips:
        zips = sorted(glob.glob(os.path.expanduser("~/Downloads/*_ue_*.zip")))
    for z in zips:
        convert(z)


if __name__ == "__main__":
    main()
