#!/usr/bin/env python3
"""make_urban_fire_levels.py — write the three urban-fire level presets from
the ONE shared urban base, so the levels differ only in the fire.

THE DEFECT THIS EXISTS TO FIX. `downtown_fire_1500`, `_lvl2` and `_lvl3` are
three independent copies of the same file. Diffed, the only layout-relevant
difference between them is `seed`, and the FIRE is byte-identical in all
three:

    downtown_fire_1500:      duration_s 28800  start_offset_frac 0.70
    downtown_fire_1500_lvl2: duration_s 28800  start_offset_frac 0.70
    downtown_fire_1500_lvl3: duration_s 28800  start_offset_frac 0.70

So the "level" ladder was never a fire ladder. Every level solved the same
fire at the same age — `elapsed_s = duration_s * start_offset_frac` = 5.6
hours, by which point every burning building is burnt out — and the levels
were then separated by `fire_city_union`'s post-hoc `rebalance_severity`,
which only reshuffles which records carry which label. That is why a "Level
1 — early / contained" manifest came back holding nothing but F4 and F5.

TWO INDEPENDENT AXES, WHICH THE OLD LADDER CONFLATED
----------------------------------------------------
*AREA* — how much of the city is involved. Set by `fire_target_frac`, which
`fire_corridor_manifest.py` turns into a corridor LENGTH (and, when the plate
runs out of run at that heading, a wider swathe). A 1 km cell whose fire
touches fourteen buildings in one corner is a 1 km cell for no reason; area
is 14 / 24 / 33 % here.

*SEVERITY* — how far each involved building has burnt. Set by the EPOCH,
`start_offset_frac`: a building an hour into its fire is F1-F2, one six
hours in is F5. This is the axis the level ladder should ride, and the only
one that should differ between L1, L2 and L3.

Both axes ride the level, because both are consequences of the same thing —
a fire that has been running longer has covered more ground AND burnt it
worse. What is NOT shared is the heading: each level runs downwind on its own
bearing (70 / 160 / 285 deg) so the three cells do not all burn along the
same diagonal.

Each level also gets its own CITY seed, chosen with `tools/pick_city_seed.py`
against the target bands — see `LEVELS`. Everything else, including every
district, layout, packing and pool key, comes from the shared base verbatim,
which is the point: three cells that differ in their fire and nothing else.

    python3 scene_gen/tools/make_urban_fire_levels.py
    python3 scene_gen/tools/make_urban_fire_levels.py --check   # diff only
"""
import argparse
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_SCENE_GEN = os.path.dirname(_HERE)
PRESETS = os.path.join(_SCENE_GEN, "config", "presets")
BASE = "downtown_urban_1000"

#: Fire top-level keys the base (a `disaster-type: none` layout preset) does
#: not carry. `epicenter` is overridden per level by the ignition seeds the
#: union picks, so the value here is only the field's default.
FIRE_COMMON = {
    "disaster-type": "fire",
    "epicenter": "[0.0, 0.0]",
    "wind_mps": "4.0",
    "duration_s": "28800",
}

#: seed  — the CITY, picked by `pick_city_seed.py` (all three score 0.00 on
#:         the target bands, and they differ in block granularity so the three
#:         cells do not read as the same town: 37 / 70 / 46 blocks). Re-picked
#:         after `layout.anisotropic.target_jitter` landed, which moved every
#:         layout; repeat share on these is 9.1 / 8.9 / 13.2 %.
#: epoch — `start_offset_frac`. THE LADDER. 0.22 / 0.45 / 0.75 of an 8 h fire
#:         is roughly 1.8 h / 3.6 h / 6.0 h elapsed.
#: seeds — ignition points. Several, spread, at EVERY level, so the burn is a
#:         city-scale event rather than one corner.
LEVELS = [
    {"level": 1, "seed": 3,  "epoch": 0.22, "heading_deg": 70.0,
     "target_frac": 0.14, "collapse": 0, "f6": 0,
     "story": "young front, ENE — many blocks alight, few burnt out"},
    {"level": 2, "seed": 18, "epoch": 0.45, "heading_deg": 160.0,
     "target_frac": 0.24, "collapse": 1, "f6": 0,
     "story": "established, SSE — burnt-out core behind the front"},
    {"level": 3, "seed": 23, "epoch": 0.75, "heading_deg": 285.0,
     "target_frac": 0.33, "collapse": 3, "f6": 1,
     "story": "severe conflagration, WNW — collapses in the tail"},
]

HEADER = """# URBAN FIRE — LEVEL {level}. {story}
#
# GENERATED by `tools/make_urban_fire_levels.py` from `{base}.yaml`. Do not
# hand-edit: edit the generator (for the fire) or the base (for the city) and
# regenerate, or the "one shared layout" guarantee silently stops holding.
#
# The city comes from the base VERBATIM — every district, layout, packing and
# pool key. The only differences from the base are the four lines below the
# marker: the city `seed`, and the fire.
#
# THE FIRE IS A WIND-DRIVEN CORRIDOR — see `disaster/fire_corridor.py`. One
# origin, one front, running downwind at `heading_deg: {heading}`; every
# building in the swathe burns, which is what keeps the burn contiguous
# instead of leaving pristine buildings inside a burnt block.
#
# `start_offset_frac: {epoch}` opens the scene at `duration_s * {epoch}` =
# {elapsed:.0f} s ({hours:.1f} h) after ignition, so the tail by the origin is
# burnt out and the head at the front is freshly alight. Both axes move with
# the level: the fire has run FURTHER ({frac:.0%} of the city here) and each
# building is FURTHER THROUGH its own fire. See the generator's docstring for
# why the old ladder — all three levels at the same 5.6 h epoch, separated
# only by a post-hoc count shuffle — produced an "early / contained" L1
# holding nothing but F4 and F5.
#
# HEADING VARIES BY LEVEL so the three cells do not all burn along the same
# diagonal.
"""


def render(level, base_text):
    elapsed = 28800 * level["epoch"]
    head = HEADER.format(level=level["level"], story=level["story"], base=BASE,
                         epoch=level["epoch"], elapsed=elapsed,
                         hours=elapsed / 3600.0,
                         heading=level["heading_deg"],
                         frac=level["target_frac"])
    body = base_text
    # strip the base's own header comment block
    lines = body.split("\n")
    i = 0
    while i < len(lines) and (lines[i].startswith("#") or not lines[i].strip()):
        i += 1
    body = "\n".join(lines[i:])

    body = re.sub(r"^seed:\s*\d+", "seed: %d" % level["seed"], body,
                  count=1, flags=re.M)
    body = re.sub(r"^disaster-type:\s*\S+", "disaster-type: fire", body,
                  count=1, flags=re.M)

    fire = ["", "# --- FIRE (the only thing that varies by level) ---------"]
    for key, val in FIRE_COMMON.items():
        if key == "disaster-type":
            continue
        fire.append("%s: %s" % (key, val))
    fire.append("heading_deg: %s" % level["heading_deg"])
    fire.append("start_offset_frac: %s" % level["epoch"])
    fire.append("")
    fire.append("# Corridor sizing, consumed by "
                "`tools/fire_corridor_manifest.py` (not by the generator).")
    fire.append("fire_target_frac: %s" % level["target_frac"])
    fire.append("fire_collapse: %s" % level["collapse"])
    fire.append("fire_f6: %s" % level["f6"])
    fire.append("")
    return head + body.rstrip("\n") + "\n" + "\n".join(fire)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing")
    a = ap.parse_args()

    base_path = os.path.join(PRESETS, BASE + ".yaml")
    base_text = open(base_path).read()
    for lv in LEVELS:
        name = "downtown_urban_fire_1000_l%d" % lv["level"]
        path = os.path.join(PRESETS, name + ".yaml")
        text = render(lv, base_text)
        if a.check:
            old = open(path).read() if os.path.exists(path) else ""
            print("%-34s %s" % (name, "UNCHANGED" if old == text
                                else ("NEW" if not old else "WOULD CHANGE")))
            continue
        with open(path, "w") as fh:
            fh.write(text)
        print("[levels] %s  (city seed %d, epoch %.2f = %.1f h, heading %.0f deg)"
              % (name, lv["seed"], lv["epoch"],
                 28800 * lv["epoch"] / 3600.0,
                 lv["heading_deg"]))
    return LEVELS


if __name__ == "__main__":
    main()
