/**:
  ros__parameters:
    use_sim_time: true
    target_frame: ws2_body_stabilized
    x_p: 1.0
    y_p: 1.0
    z_p: 1.0
    x_min: -0.35
    x_max: 0.35
    y_min: -0.35
    y_max: 0.35
    z_min: -0.25
    z_max: 0.25
    vx_p: 0.2
    vx_i: 0.025
    vx_min: -0.2
    vx_max: 0.2
    vy_p: 0.2
    vy_i: 0.025
    vy_min: -0.2
    vy_max: 0.2
    vz_p: 0.2
    vz_i: 0.1
    vz_min: 0.0
    vz_max: 1.0
    vz_constant: 0.5
    max_roll_pitch: 10.0
    x_i: 0.0
    x_d: 0.0
    x_ff: 0.0
    x_d_alpha: 0.0
    x_constant: 0.0
    y_i: 0.0
    y_d: 0.0
    y_ff: 0.0
    y_d_alpha: 0.0
    y_constant: 0.0
    z_i: 0.0
    z_d: 0.0
    z_ff: 0.0
    z_d_alpha: 0.0
    z_constant: 0.0
    vx_d: 0.0
    vx_ff: 0.0
    vx_d_alpha: 0.0
    vx_constant: 0.0
    vy_d: 0.0
    vy_ff: 0.0
    vy_d_alpha: 0.0
    vy_constant: 0.0
    vz_d: 0.0
    vz_ff: 0.0
    vz_d_alpha: 0.0
