base_link_frame_id: "base_link"
camera_list:
  - camera_name: "front_stereo"
    camera_type: "stereo"
    left_camera_info_sub_topic: "/robot_1/sensors/front_stereo/left/camera_info"
    right_camera_info_sub_topic: "/robot_1/sensors/front_stereo/right/camera_info"
    left_camera_frame_id: "left" 
    right_camera_frame_id: "right"

# LiDAR sensor configuration
# lidar_list:
#   - lidar_name: "ouster"
#     lidar_type: "RTX_lidar"
#     sensor_configuration: "Velodyne_VLS128" # Available configs: Velodyne_VLS128, OS1_64, etc.
#     position: [0.0, 0.0, 0.15]  # X, Y, Z offset from vehicle center in meters
#     orientation: [0.0, 0.0, 0.0]  # Roll, Pitch, Yaw in degrees
#     frequency: 60.0  # Hz
#     show_render: false  # Show debug visualization in Isaac Sim
#     topic: "sensors/ouster/point_cloud"  # Expected by VDB mapping
