# Instructions: 

# Build: docker-compose build --no-cache
# Run as interactive mode:  docker run -it --rm tak_tools_ros2cot_agent /bin/bash

version: '3.8'


services:
################### MQTT
  mqtt:
    container_name: "mqtt"
    image: eclipse-mosquitto:2.0.20
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "ping", "-u", "${MQTT_USERNAME}", "-P", "${MQTT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s
    networks:
      - basestation-network

################## ROS2COT_AGENT 
  ros2cot_agent:
    build:
      context: ../
      dockerfile: ros2tak_tools/ros2tak_tools/Dockerfile.ros2cot_agent
    container_name: "${PROJECT_NAME}_ros2cot_agent"
    volumes: 
      - ./config:/home/mission-operator/ros2_ws/src/ros2tak_tools/config
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mqtt:
        condition: service_healthy
    networks:
      - basestation-network
    command: ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /home/mission-operator/ros2_ws/install/setup.bash && ros2 run ros2tak_tools ros2cot_agent --config $CONFIG_PATH"]

# ################### TAK_PUBLISHER
  tak_publisher:
    build:
      context: ../
      dockerfile: ros2tak_tools/scripts/Dockerfile.tak_publisher
    container_name: "${PROJECT_NAME}_tak_publisher"
    volumes: 
      - ./config:/home/mission-operator/ros2_ws/src/ros2tak_tools/config
      - ./scripts:/home/mission-operator/ros2_ws/src/ros2tak_tools/scripts
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mqtt:
        condition: service_healthy
    networks:
      - basestation-network
    command: ["python3", "$TAK_PUBLISHER_FILE_PATH", "--config", "$CONFIG_PATH"]

################### TAK_SUBSCRIBER
  tak_subscriber:
    build:
      context: ../
      dockerfile: ros2tak_tools/scripts/Dockerfile.tak_subscriber
    container_name: "${PROJECT_NAME}_tak_subscriber"
    volumes: 
      - ./config:/home/mission-operator/ros2_ws/src/ros2tak_tools/config
      - ./scripts:/home/mission-operator/ros2_ws/src/ros2tak_tools/scripts
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mqtt:
        condition: service_healthy
    networks:
      - basestation-network
    command: ["python3", "$TAK_SUBSCRIBER_FILE_PATH", "--config", "$CONFIG_PATH"]


########### NETWORKS ###########
networks:
  basestation-network:
    driver: bridge 

