# Copyright (c) 2026 Carnegie Mellon University
# MIT License - see LICENSE in the repository root for full text.
"""Stack folder anatomy contract (RFC #379 §3, RFC #385 §1).

Every stack directory under ``stacks/`` (ignoring ``.external``, the gitignored
home of fetched third-party stack repos) must ship the four committed anatomy
files:

* ``modules.repos`` — YAML with a top-level ``airstack_compat`` semver range
  (sibling of ``repositories:``; vcstool ignores it, our tooling reads it);
* ``launch/`` — at least one ``*.launch.xml`` entry point;
* ``docker-compose.yaml`` — valid YAML (a documented stub until module pins
  arrive);
* ``README.md`` — non-trivial.

``wiring.md`` is NOT required yet (bootstrap: it is generated from the first
validated wiring-snapshot run), but when present it must carry the
machine-readable ``wiring-graph-v1`` trailer that the drift check reads.
"""
import pytest
import yaml

from harness.discovery import TESTS_DIR

pytestmark = pytest.mark.unit

REPO = TESTS_DIR.parent
STACKS_DIR = REPO / "stacks"


def _stack_dirs():
    if not STACKS_DIR.is_dir():
        return []
    return sorted(
        d for d in STACKS_DIR.iterdir()
        if d.is_dir() and not d.name.startswith(".")
    )


def _stack_ids():
    return [d.name for d in _stack_dirs()]


def test_stacks_dir_has_reference_stacks():
    assert _stack_dirs(), (
        f"{STACKS_DIR} has no stack folders — trunk ships reference stacks "
        "(full_default, ...)"
    )


@pytest.mark.parametrize("stack", _stack_dirs(), ids=_stack_ids())
class TestStackAnatomy:

    def test_modules_repos(self, stack):
        path = stack / "modules.repos"
        assert path.is_file(), f"{stack.name}: missing modules.repos"
        data = yaml.safe_load(path.read_text())
        assert isinstance(data, dict), (
            f"{stack.name}: modules.repos did not parse to a YAML mapping"
        )
        compat = data.get("airstack_compat")
        assert isinstance(compat, str) and compat.strip(), (
            f"{stack.name}: modules.repos needs a top-level airstack_compat "
            "semver-range string (the trunk range the stack was tested "
            "against — RFC #379 §3)"
        )
        assert "repositories" in data, (
            f"{stack.name}: modules.repos needs a repositories: key "
            "(vcstool format; {} when the stack pins no modules)"
        )

    def test_launch_entry_points(self, stack):
        launch_dir = stack / "launch"
        assert launch_dir.is_dir(), f"{stack.name}: missing launch/ dir"
        entries = list(launch_dir.glob("*.launch.xml"))
        assert entries, (
            f"{stack.name}: launch/ has no *.launch.xml entry point "
            "(unsplit stacks have exactly stack.launch.xml)"
        )

    def test_docker_compose_is_valid_yaml(self, stack):
        path = stack / "docker-compose.yaml"
        assert path.is_file(), f"{stack.name}: missing docker-compose.yaml"
        data = yaml.safe_load(path.read_text())
        assert data is not None, (
            f"{stack.name}: docker-compose.yaml is empty — keep at least "
            "'services: {}' plus the explanatory comments"
        )

    def test_readme_non_trivial(self, stack):
        path = stack / "README.md"
        assert path.is_file(), f"{stack.name}: missing README.md"
        text = path.read_text().strip()
        assert len(text) >= 200, (
            f"{stack.name}: README.md is trivial ({len(text)} chars) — state "
            "what the stack is for, how to run it, and its known limits"
        )

    def test_wiring_md_trailer_when_present(self, stack):
        """wiring.md is optional (bootstrap) but must be machine-readable."""
        path = stack / "wiring.md"
        if not path.exists():
            pytest.skip(f"{stack.name}: wiring.md not committed yet "
                        "(generated by the first wiring-snapshot run)")
        import wiring_snapshot as ws
        try:
            graph = ws.extract_graph_from_md(path.read_text())
        except ValueError as exc:
            pytest.fail(
                f"{stack.name}: wiring.md lacks a parseable wiring-graph-v1 "
                f"trailer ({exc}) — regenerate it from a wiring-snapshot "
                "run, never hand-edit"
            )
        assert graph.get("nodes") is not None, (
            f"{stack.name}: wiring.md trailer has no nodes key — regenerate "
            "it from a wiring-snapshot run"
        )
