services:
  airsim:
    profiles:
      - airsim
    image: &airsim_image ${PROJECT_DOCKER_REGISTRY}/${PROJECT_NAME}:v${DOCKER_IMAGE_TAG}_airsim
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - *airsim_image
    entrypoint: ""
    command: >
      bash -c "
      python3 /home/airsim/Documents/AirSim/generate_settings.py &&
      tmux new -d -s airsim &&
      for i in $$(seq 1 $$NUM_ROBOTS); do
        tmux new-window -t airsim &&
        tmux send-keys -t airsim \"cd /root/PX4-Autopilot && PX4_SIM_MODEL=none_iris ./build/px4_sitl_default/bin/px4 ./ROMFS/px4fmu_common -s ROMFS/px4fmu_common/init.d-posix/rcS -i $$i\" ENTER;
      done &&
      tmux new-window -t airsim &&
      tmux send-keys -t airsim 'sudo -u airsim $$AIRSIM_BINARY_PATH' ENTER &&
      cd /root/ros_ws && colcon build --symlink-install &&
      for i in $$(seq 1 $$NUM_ROBOTS); do
        tmux new-window -t airsim &&
        tmux send-keys -t airsim \"source /root/ros_ws/install/setup.bash && ROS_DOMAIN_ID=$$i ros2 run airsim_ros_bridge bridge_node --ros-args -p robot_name:=robot_$$i\" ENTER;
      done &&
      sleep infinity"
    stdin_open: true
    tty: true
    ipc: host
    privileged: true
    networks:
      airstack_network:
        ipv4_address: 172.31.0.201
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=/tmp
      - NUM_ROBOTS=${NUM_ROBOTS:-1}
      - AUTOLAUNCH=${AUTOLAUNCH:-true}
      - AIRSIM_BINARY_PATH=${AIRSIM_BINARY_PATH:-/airsim_env/LinuxNoEditor/Blocks.sh}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../config:/home/airsim/Documents/AirSim:rw
      - ../ros_ws:/root/ros_ws:rw
      - ${AIRSIM_ENV_DIR:-../environments}:/airsim_env:rw
      - /usr/share/vulkan/icd.d/nvidia_icd.json:/usr/share/vulkan/icd.d/nvidia_icd.json:ro