# docker compose file
services:
  robot_base:
    # Interactive shell
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # Needed to display graphical applications
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Record bags
      - RECORD_BAGS=${RECORD_BAGS}
      # docker compose interpolation to env variables
      - LAUNCH_PACKAGE=${LAUNCH_PACKAGE}
      - AUTONOMY_MODE=${AUTONOMY_MODE:-onboard_all}
      - ROBOT_LAUNCH_FILE=${ROBOT_LAUNCH_FILE}
      - ROBOT_URDF_FILE=${ROBOT_URDF_FILE}  
      # MAVROS
      - OFFBOARD_BASE_PORT=${OFFBOARD_BASE_PORT}
      - ONBOARD_BASE_PORT=${ONBOARD_BASE_PORT}
      - ROBOT_NAME_MAP_CONFIG_FILE=${ROBOT_NAME_MAP_CONFIG_FILE:-default_robot_name_map.yaml}
    volumes:
      # display stuff
      - $HOME/.Xauthority:/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      # developer stuff
      - .dev:/root/.dev:rw # developer config
      - ../../common/.bash_profile:/root/.bash_profile:rw  # commented out - common/ no longer exists
      - .bashrc:/root/.bashrc:rw # bash config
      - ../../common/inputrc:/etc/inputrc:rw  # commented out - common/ no longer exists
      - ../../common/.tmux.conf:/root/.tmux.conf:rw  # commented out - common/ no longer exists
      - ../../.devcontainer/robot/launch.json:/root/AirStack/.vscode/launch.json:rw
      - ../../.devcontainer/robot/tasks.json:/root/AirStack/.vscode/tasks.json:rw
      # autonomy stack stuff
      - ../..:/root/AirStack
      # bags
      - ../bags:/bags:rw

