/**:
  ros__parameters:
    world_frame_id: "map"
    robot_frame_id: "base_link"
    pub_global_trajectory_topic: "/global/trajectory"
    pub_goal_point_viz_topic: "/global/goal_point_viz"
    pub_trajectory_viz_topic: "/global/traj_viz"
    sub_map_topic: "/vdb_mapping/vdb_map_visualization"
    sub_robot_tf_topic: "/tf"
    srv_random_walk_toggle_topic: "/robot_1/behavior/global_plan_toggle"

    publish_visualizations: false # should trajectory visualizations be published
    num_paths_to_generate: 5 # how many paths to generate

    # Constants
    max_start_to_goal_dist_m: 10.0 # how max distance the goal can be from the current robot position
    checking_point_cnt: 1000 # how many points to collision check between the start and goal points
    max_z_m: 0.1 # max height that the goal can deviate from the current height
    collision_padding_m: 0.1 # how much space should the path have to any obstacles
    path_end_threshold_m: 0.1 # how close to the goal will the path be considered complete

