/**:
  ros__parameters:
    world_frame_id: "/map"
    pub_global_path_topic: "/global/planning/trajectory"
    pub_goal_point_topic: "/global/planning/goal_point"
    pub_trajectory_lines_topic: "/global/planning/traj_viz"
    sub_map_topic: "/vdb_mapping/vdb_map_visualization"
    sub_robot_tf_topic: "/global/tf"
    srv_get_path_service: "/global/planning/get_path"

    publish_visualizations: true # should trajectory visualizations be published

    # Constants
    max_start_to_goal_dist_m: 3.5 # how max distance the goal can be from the current robot position
    checking_point_cnt: 1000 # how many points to collision check between the start and goal points
    max_z_m: 0.1 # max height that the goal can deviate from the current height
    collision_padding_m: 0.1 # how much space should the path have to any obstacles
    path_end_threshold_m: 0.1 # how close to the goal will the path be considered complete

