launch_config:
  renderer: RaytracedLighting
  headless: false
resolution: [512, 512]
env_url: "/Isaac/Environments/Grid/default_environment.usd"
rt_subframes: 32
writer: BasicWriter
writer_config:
  output_dir: _out_basicwriter
  rgb: true