launch_config:
  renderer: RaytracedLighting
  headless: true
resolution: [512, 512]
num_frames: 5
clear_previous_semantics: false
writer: KittiWriter
writer_config:
  output_dir: _out_kitti
  colorize_instance_segmentation: true
  mapping_dict:
    forklift: [11, 110, 223, 255]
    pallet: [211, 210, 223, 255]