#!/usr/bin/env python

import sys

from rqt_behavior_tree.rqt_behavior_tree import BehaviorTreePlugin
from rqt_gui.main import Main

plugin = 'rqt_behavior_tree'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
