# Base image with Python 3
FROM python:3.10-slim

# Set working directory
WORKDIR /home/mission-operator/ros2_ws/

# Install necessary dependencies
# Install necessary dependencies
RUN pip install --no-cache-dir asyncio pytak pyyaml cryptography paho-mqtt

# Copy the local 'ros2tak_tools' directory into the container
COPY ../ros2tak_tools /home/mission-operator/ros2_ws/src/ros2tak_tools/
