#!/usr/bin/env python3
# Copyright (c) 2026 Carnegie Mellon University
# SPDX-License-Identifier: BSD-3-Clause-Clear
"""Place synced AirStack modules into the trunk checkout (RFC #379 §3, Phase P2).

``airstack module sync`` clones/links module repos into the gitignored
``modules/`` directory at the repo root. This tool performs the *overlay*: by
manifest ``type``/``targets`` it places each module where the build systems and
containers can see it, and it regenerates the compose override that makes the
placements resolve **inside** the containers.

What it places, per module under ``modules/<name>/``:

- ``ros_package`` targeting ``robot`` → symlink
  ``robot/ros_ws/src/modules/<name>`` → ``../../../../modules/<name>`` so colcon
  (host-side and in-container) picks the packages up. The robot container only
  mounts ``robot/ros_ws`` (see robot/docker/robot-base-docker-compose.yaml), so
  that symlink would DANGLE in-container; the generated compose file therefore
  bind-mounts the module checkout at ``/root/AirStack/modules/<name>`` — the
  symlink's in-container resolution target.

- ``isaac_extension`` targeting ``isaac-sim`` → symlink every
  ``modules/<name>/launch_scripts/*.py`` into
  ``simulation/isaac-sim/launch_scripts/modules/<name>/``. The isaac container
  mounts the whole repo at ``/isaac-sim/AirStack``, so these repo-internal
  symlinks resolve in-container (local-path modules — where ``modules/<name>``
  is itself a symlink out of the repo — additionally get a bind mount at
  ``/isaac-sim/AirStack/modules/<name>``). Launch scripts become addressable as
  ``ISAAC_SIM_SCRIPT_NAME=modules/<name>/<script>.py``. Kit extensions under
  ``modules/<name>/exts/*`` are mounted into the shared Kit exts dir the isaac
  command already passes via ``--ext-folder`` (same pattern as
  ``optitrack.natnet.emulator``).

- a manifest ``compose:`` fragment → merged verbatim into the generated file,
  with relative host paths rewritten to absolute (compose files resolve
  relative bind sources against ambiguous bases when merged via ``-f``; the
  generated file is machine-local and regenerated on every sync, so absolute
  paths are the unambiguous choice). When a fragment is declared it is the
  source of truth for that module's mounts — the ``exts/`` auto-mount is
  skipped to avoid double mounts (the dfm2 pilot's friction log, item 5).

- ``data`` / other types → no overlay action yet (noted).

The generated file is ``.airstack/generated/docker-compose.modules.yaml``
(gitignored). Until `airstack up` grows automatic wiring (Phase P4/P5), pass it
explicitly::

    airstack up -f .airstack/generated/docker-compose.modules.yaml

CLI::

    module_overlay.py [--project-root DIR]            # sync (default): idempotent
    module_overlay.py --remove NAME [--project-root]  # drop NAME's artifacts
    module_overlay.py --check [--project-root]        # verify links + compose freshness

Exit 0 on success / clean check; 1 on failure or a dirty check.
"""
import argparse
import os
import sys
from pathlib import Path

import yaml

MANIFEST_NAME = "module.yaml"
GENERATED_REL = Path(".airstack/generated/docker-compose.modules.yaml")
ROBOT_LINK_REL = Path("robot/ros_ws/src/modules")
ISAAC_LINK_REL = Path("simulation/isaac-sim/launch_scripts/modules")
MODULES_REL = Path("modules")

# Container-side paths (contracts with the trunk compose files).
ROBOT_CONTAINER_MODULES = "/root/AirStack/modules"          # robot/docker/robot-base-docker-compose.yaml mounts ../ros_ws at /root/AirStack/robot/ros_ws
ISAAC_CONTAINER_REPO = "/isaac-sim/AirStack"                # simulation/isaac-sim/docker/docker-compose.yaml mounts ../../.. here
KIT_SHARED_EXTS = "/isaac-sim/.local/share/ov/data/documents/Kit/shared/exts"
LAUNCH_SCRIPTS_ENV = (
    "AIRSTACK_LAUNCH_SCRIPTS_DIR="
    f"{ISAAC_CONTAINER_REPO}/simulation/isaac-sim/launch_scripts"
)

# Robot services the module volumes are attached to. Services that `extends:`
# these from another compose *file* (robot-desktop-onboard, robot-offboard, …)
# re-parse the base file and do NOT inherit override-file additions — a known
# v1 limitation, documented in docs/development/modules.md.
DEFAULT_ROBOT_SERVICES = ("robot-desktop", "robot-l4t")

HEADER = """\
# GENERATED by tools/module_overlay.py (`airstack module sync`) — DO NOT EDIT.
# Regenerated on every sync; gitignored. Host paths are absolute on purpose:
# relative bind sources resolve against different bases depending on how the
# file is merged, and this file never leaves this machine.
#
# Use it by appending it to the compose file list:
#   airstack up -f .airstack/generated/docker-compose.modules.yaml
"""


def log(msg):
    print(f"[overlay] {msg}")


class OverlayError(Exception):
    pass


# ── discovery ────────────────────────────────────────────────────────────────

def discover_modules(root, exclude=()):
    """Map <checkout-dir-name> → manifest for every modules/<name>/module.yaml."""
    modules = {}
    modules_dir = root / MODULES_REL
    if not modules_dir.is_dir():
        return modules
    for child in sorted(modules_dir.iterdir()):
        if child.name in exclude:
            continue
        manifest_path = child / MANIFEST_NAME
        if not child.is_dir():  # follows symlinks; dangling links land here
            if child.is_symlink():
                log(f"warning: {child} is a dangling symlink — skipping (re-run `airstack module sync`)")
            continue
        if not manifest_path.is_file():
            log(f"warning: {child} has no {MANIFEST_NAME} — skipping")
            continue
        try:
            manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            raise OverlayError(f"{manifest_path}: invalid YAML: {exc}")
        if not isinstance(manifest, dict):
            raise OverlayError(f"{manifest_path}: manifest top level must be a mapping")
        modules[child.name] = manifest
    return modules


# ── desired state ────────────────────────────────────────────────────────────

def desired_robot_links(root, modules):
    """{link_path: relative_target} for ros_package modules targeting robot."""
    links = {}
    link_dir = root / ROBOT_LINK_REL
    for name, manifest in modules.items():
        if manifest.get("type") != "ros_package":
            continue
        if "robot" not in (manifest.get("targets") or []):
            continue
        link = link_dir / name
        target = os.path.relpath(root / MODULES_REL / name, link_dir)
        links[link] = target
    return links


def desired_isaac_links(root, modules):
    """{link_path: relative_target} for module Isaac launch scripts.

    Keyed off targets, not type: a ros_package module that also targets
    isaac-sim (e.g. optitrack: robot client + in-sim emulator) ships launch
    scripts too.
    """
    links = {}
    for name, manifest in modules.items():
        if "isaac-sim" not in (manifest.get("targets") or []):
            continue
        scripts_dir = root / MODULES_REL / name / "launch_scripts"
        if not scripts_dir.is_dir():
            continue
        module_link_dir = root / ISAAC_LINK_REL / name
        for script in sorted(scripts_dir.glob("*.py")):
            link = module_link_dir / script.name
            links[link] = os.path.relpath(script, module_link_dir)
    return links


def _abs_host_path(src, base_dir):
    """Rewrite a compose bind source relative to ``base_dir`` into an absolute path."""
    if src.startswith(("./", "../")):
        return os.path.normpath(str(base_dir / src))
    return src


def _merge_service(target, source, module_dir):
    """Merge one compose service definition into ``target`` (fragment semantics)."""
    for key, value in source.items():
        if key == "volumes" and isinstance(value, list):
            merged = target.setdefault("volumes", [])
            for entry in value:
                if isinstance(entry, str):
                    parts = entry.split(":")
                    parts[0] = _abs_host_path(parts[0], module_dir)
                    entry = ":".join(parts)
                elif isinstance(entry, dict) and entry.get("type", "bind") == "bind" and "source" in entry:
                    entry = {**entry, "source": _abs_host_path(entry["source"], module_dir)}
                if entry not in merged:
                    merged.append(entry)
        elif isinstance(value, list):
            merged = target.setdefault(key, [])
            for entry in value:
                if entry not in merged:
                    merged.append(entry)
        elif isinstance(value, dict):
            target.setdefault(key, {}).update(value)
        else:
            target[key] = value


def build_compose(root, modules, robot_services):
    """Compose override mapping (or None when there is nothing to declare)."""
    services = {}

    def add_volume(service, entry):
        volumes = services.setdefault(service, {}).setdefault("volumes", [])
        if entry not in volumes:
            volumes.append(entry)

    any_isaac = False
    for name, manifest in modules.items():
        module_link = root / MODULES_REL / name          # possibly a symlink (local-path module)
        module_real = Path(os.path.realpath(module_link))
        mtype = manifest.get("type")
        targets = manifest.get("targets") or []

        if mtype == "ros_package" and "robot" in targets:
            for service in robot_services:
                add_volume(service, f"{module_real}:{ROBOT_CONTAINER_MODULES}/{name}:rw")

        # Keyed off targets, not type — hybrid modules (ros_package + isaac-sim
        # target, e.g. optitrack's client + emulator) need the same placement.
        if "isaac-sim" in targets:
            any_isaac = True
            # Local-path modules: modules/<name> is a symlink out of the repo,
            # which dangles inside the whole-repo mount — bind the real dir at
            # the in-container path the launch-script symlinks resolve to.
            if module_link.is_symlink():
                add_volume(
                    "isaac-sim",
                    f"{module_real}:{ISAAC_CONTAINER_REPO}/modules/{name}:rw",
                )
            # Kit extensions: fragment (if declared) is the source of truth;
            # otherwise auto-mount every exts/* dir into the shared exts dir.
            if not manifest.get("compose"):
                exts_dir = module_link / "exts"
                if exts_dir.is_dir():
                    for ext in sorted(exts_dir.iterdir()):
                        if ext.is_dir():
                            add_volume(
                                "isaac-sim",
                                f"{module_real / 'exts' / ext.name}:{KIT_SHARED_EXTS}/{ext.name}/:rw",
                            )

        if mtype == "data":
            log(f"module '{name}' is type data — no overlay action yet (assets fetch lands later)")

        fragment_rel = manifest.get("compose")
        if fragment_rel:
            fragment_path = module_link / fragment_rel
            if not fragment_path.is_file():
                raise OverlayError(f"{name}: declared compose fragment not found: {fragment_path}")
            fragment = yaml.safe_load(fragment_path.read_text(encoding="utf-8")) or {}
            for service_name, service_def in sorted((fragment.get("services") or {}).items()):
                _merge_service(
                    services.setdefault(service_name, {}), service_def, module_real
                )

    if any_isaac:
        env = services.setdefault("isaac-sim", {}).setdefault("environment", [])
        if LAUNCH_SCRIPTS_ENV not in env:
            env.append(LAUNCH_SCRIPTS_ENV)

    if not services:
        return None
    return {"services": services}


def render_compose(compose):
    return HEADER + yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)


# ── filesystem actions ───────────────────────────────────────────────────────

def _is_overlay_symlink(path, root):
    """True when ``path`` is a symlink pointing into the repo's modules/ dir."""
    if not path.is_symlink():
        return False
    resolved = Path(os.path.normpath(path.parent / os.readlink(path)))
    try:
        resolved.relative_to(root / MODULES_REL)
    except ValueError:
        return False
    return True


def warn_stale_colcon_caches(root, modules):
    """Warn when a module package has a colcon cache built from another path.

    A package extracted from trunk into a module (e.g. natnet_ros2:
    perception/ → modules/asm_optitrack/) keeps its old
    robot/ros_ws/build/<pkg>/ CMake cache in bind-mounted checkouts; colcon
    then fails with "source ... does not match the source ... used to
    generate cache". Observe-and-report only (build artifacts are typically
    root-owned from the container, so we print the fix, not run it).
    """
    ws = root / "robot" / "ros_ws"
    stale = []
    for name in modules:
        module_dir = root / MODULES_REL / name
        for pkg_xml in module_dir.glob("**/package.xml"):
            try:
                import xml.etree.ElementTree as ET
                pkg = ET.parse(pkg_xml).findtext("name")
            except Exception:
                continue
            if not pkg:
                continue
            cache = ws / "build" / pkg / "CMakeCache.txt"
            if cache.is_file():
                try:
                    text = cache.read_text(encoding="utf-8", errors="replace")
                except OSError:
                    continue
                if "/src/modules/" not in text:
                    stale.append(pkg)
    if stale:
        pkgs = " ".join(f"/ws/build/{p} /ws/install/{p}" for p in sorted(set(stale)))
        log(f"WARNING: stale colcon cache(s) for module package(s) "
            f"{sorted(set(stale))} — built from a pre-extraction source path; "
            f"colcon will fail until removed. Fix (root-owned artifacts):")
        log(f"  docker run --rm -v \"$PWD/robot/ros_ws:/ws\" ubuntu:24.04 "
            f"bash -c 'rm -rf {pkgs}'")


def apply_links(desired, link_root, repo_root):
    """Create/refresh desired symlinks; drop stale overlay symlinks under link_root."""
    changed = False
    for link, target in sorted(desired.items()):
        link.parent.mkdir(parents=True, exist_ok=True)
        if link.is_symlink():
            if os.readlink(link) == target:
                continue
            link.unlink()
        elif link.exists():
            raise OverlayError(
                f"{link} exists and is not a symlink — refusing to replace "
                "(in-tree module with the same name? rename one of them)"
            )
        link.symlink_to(target)
        log(f"link {link} -> {target}")
        changed = True

    # Stale cleanup: only symlinks that point into modules/ are ours to remove.
    if link_root.is_dir():
        desired_set = set(desired)
        for current, _dirs, files in os.walk(link_root, topdown=False):
            current = Path(current)
            for entry in files + [d for d in _dirs]:
                path = current / entry
                if path in desired_set:
                    continue
                if _is_overlay_symlink(path, repo_root):
                    path.unlink()
                    log(f"removed stale link {path}")
                    changed = True
            # also handle direct symlinked dirs listed as dirs by walk
        # prune now-empty directories (bottom-up), leaving real content alone
        for current, _dirs, _files in os.walk(link_root, topdown=False):
            current = Path(current)
            try:
                current.rmdir()
            except OSError:
                pass
    return changed


def check_links(desired, link_root, repo_root, problems):
    for link, target in sorted(desired.items()):
        if not link.is_symlink():
            problems.append(f"missing symlink: {link} -> {target}")
        elif os.readlink(link) != target:
            problems.append(f"wrong symlink target: {link} -> {os.readlink(link)} (want {target})")
        elif not link.exists():
            problems.append(f"dangling symlink: {link} -> {target}")
    if link_root.is_dir():
        desired_set = set(desired)
        for current, dirs, files in os.walk(link_root):
            current = Path(current)
            for entry in files + dirs:
                path = current / entry
                if path not in desired_set and _is_overlay_symlink(path, repo_root):
                    problems.append(f"stale overlay symlink: {path}")


# ── entry point ──────────────────────────────────────────────────────────────

def run(root, mode="sync", remove=None, robot_services=None):
    root = Path(root).resolve()
    robot_services = list(robot_services or DEFAULT_ROBOT_SERVICES)
    exclude = (remove,) if remove else ()
    modules = discover_modules(root, exclude=exclude)

    robot_links = desired_robot_links(root, modules)
    isaac_links = desired_isaac_links(root, modules)
    compose = build_compose(root, modules, robot_services)
    generated = root / GENERATED_REL

    if mode == "check":
        problems = []
        check_links(robot_links, root / ROBOT_LINK_REL, root, problems)
        check_links(isaac_links, root / ISAAC_LINK_REL, root, problems)
        if compose is None:
            if generated.exists():
                problems.append(f"{generated} exists but no module declares anything — stale")
        else:
            if not generated.exists():
                problems.append(f"{generated} is missing — run `airstack module sync`")
            elif generated.read_text(encoding="utf-8") != render_compose(compose):
                problems.append(f"{generated} is out of date — run `airstack module sync`")
        for problem in problems:
            log(f"PROBLEM: {problem}")
        if problems:
            return 1
        log(f"overlay OK ({len(modules)} module(s), {len(robot_links)} robot link(s), "
            f"{len(isaac_links)} isaac launch-script link(s))")
        return 0

    # sync / remove
    apply_links(robot_links, root / ROBOT_LINK_REL, root)
    apply_links(isaac_links, root / ISAAC_LINK_REL, root)
    warn_stale_colcon_caches(root, modules)

    if compose is None:
        if generated.exists():
            generated.unlink()
            log(f"removed {generated} (no modules declare container placements)")
        try:
            generated.parent.rmdir()
        except OSError:
            pass
    else:
        text = render_compose(compose)
        if not generated.exists() or generated.read_text(encoding="utf-8") != text:
            generated.parent.mkdir(parents=True, exist_ok=True)
            generated.write_text(text, encoding="utf-8")
            log(f"wrote {generated} ({len(compose['services'])} service(s))")
        else:
            log(f"{generated} up to date")

    log(f"overlay complete: {len(modules)} module(s)")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--project-root", default=str(Path(__file__).resolve().parents[1]),
                        help="AirStack checkout root (default: parent of tools/)")
    parser.add_argument("--check", action="store_true",
                        help="verify symlinks and generated-compose freshness; exit 1 on drift")
    parser.add_argument("--remove", metavar="NAME",
                        help="drop NAME's overlay artifacts and regenerate for the rest")
    parser.add_argument("--robot-services",
                        default=os.environ.get("AIRSTACK_MODULE_ROBOT_SERVICES",
                                               ",".join(DEFAULT_ROBOT_SERVICES)),
                        help="comma-separated robot compose services to attach module volumes to")
    args = parser.parse_args(argv)

    robot_services = [s.strip() for s in args.robot_services.split(",") if s.strip()]
    try:
        return run(
            args.project_root,
            mode="check" if args.check else "sync",
            remove=args.remove,
            robot_services=robot_services,
        )
    except OverlayError as exc:
        log(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
