# Base image with ROS2 Humble
# Base image with ROS2 Humble
FROM ros:humble

# Set working directory
WORKDIR /home/mission-operator/ros2_ws

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    ros-humble-ros2cli \
    python3-pip \
    libglib2.0-dev && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Python dependencies
RUN pip3 install --upgrade pip \
    && pip3 install setuptools==57.5.0 pytak pyyaml \
    && pip3 install paho-mqtt

# Copy the local 'ros2tak_tools' directory into the container
COPY ../../ros2tak_tools /home/mission-operator/ros2_ws/src/ros2tak_tools

# Build the ROS2 workspace
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
                  colcon build --symlink-install"

# Source the ROS 2 environment in .bashrc
RUN echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc && \
    echo 'source /home/mission-operator/ros2_ws/install/setup.bash' >> ~/.bashrc

