defaults:
  - _self_
  - override mapping: "semantic_ray_frontiers_map"
  - override encoder: "radseg"
  - override vis: ros
  - override messaging_service: ros
  - override feat_compressor: null # Set to null to disable
  - extras

# Disable logging to files
hydra:
  output_subdir: null
  run:
    dir: .

dataset:
  frame_skip: 2
# How many frames should be batched before processing.
batch_size: 1

# Imposing a depth limit on the data such that to test limited depth scenarios
# Set to a negative number to not use a limit
depth_limit: 70

# Which pytorch interpolation mode for rgb and feature interpolation 
# (Depth and Segmentation always use nearest-exact)
interp_mode: bilinear

querying:

  # Whether to query in compressed feature space or decompress first. Only used
  # if feat_compressor was used.
  compressed: False

  # Whether softmax probability is computed across queries or not.
  # If you want results to be independent of other queries set this to false.
  # Image queries are seperated from text queries. i.e the softmax is computed
  # separately for the text query group and the image query group.
  compute_prob: True

  # How often should the mapping server update query results in the map.
  period: 10

seed: 17