#!/usr/bin/env python3
"""Aggregate the per-project defects.csv files (Stage 2 of the defect-mining study)
into the class x venue tables reported in Sec. VI-B, validating the schema on the way.

    python3 summarize_defects.py results/*/defects.csv hummingbird/defects.csv --out results
    python3 summarize_defects.py ... --verify AirStack-core=repos/AirStack Shimizu=repos/AirStack

--verify NAME=PATH checks that every commit_sha of project NAME resolves in the local clone
at PATH (auditability check; rows that fail are listed, not dropped).
"""
from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

HEADER = ["project", "repo", "defect_id", "date", "evidence_type", "evidence_url", "commit_sha", "defect_class",
          "class_confidence", "discovery_venue", "venue_confidence", "description", "evidence_quote",
          "experiment_ruining_proposed", "ruining_rationale", "fix_files", "fix_loc"]
CLASSES = ["remap_topic", "tf_frame", "parameter", "timing_clock", "build", "logic", "other"]
VENUES = ["ci_premerge", "sim_interactive", "bench_hardware", "field", "unknown"]
CONF = {"high", "medium", "low"}
RUIN = {"yes", "no", "uncertain"}
EVID = {"ci_run", "pr_thread", "commit_msg", "issue", "notes_file"}
INTEGRATION = {"remap_topic", "tf_frame", "parameter", "timing_clock", "build"}


def load(path: Path) -> list:
    with path.open(newline="", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        if rd.fieldnames != HEADER:
            sys.exit(f"{path}: header mismatch\n got {rd.fieldnames}\n want {HEADER}")
        rows = list(rd)
    errs = []
    for r in rows:
        if r["defect_class"] not in CLASSES: errs.append(f"{r['defect_id']}: class {r['defect_class']}")
        if r["discovery_venue"] not in VENUES: errs.append(f"{r['defect_id']}: venue {r['discovery_venue']}")
        if r["class_confidence"] not in CONF or r["venue_confidence"] not in CONF: errs.append(f"{r['defect_id']}: confidence")
        if r["experiment_ruining_proposed"] not in RUIN: errs.append(f"{r['defect_id']}: ruining {r['experiment_ruining_proposed']}")
        if r["evidence_type"] not in EVID: errs.append(f"{r['defect_id']}: evidence_type {r['evidence_type']}")
        if not r["evidence_url"] or not r["commit_sha"]: errs.append(f"{r['defect_id']}: missing evidence_url/commit_sha")
    if errs:
        sys.exit(f"{path}: schema errors:\n  " + "\n  ".join(errs))
    return rows


def table(rows: list) -> str:
    grid = defaultdict(Counter)
    for r in rows:
        grid[r["defect_class"]][r["discovery_venue"]] += 1
    L = ["| class | " + " | ".join(f"`{v}`" for v in VENUES) + " | total |", "|---|" + "---:|" * (len(VENUES) + 1)]
    tot = Counter()
    for c in CLASSES:
        row = grid.get(c, Counter())
        if not row:
            continue
        L.append(f"| `{c}` | " + " | ".join(str(row[v]) for v in VENUES) + f" | **{sum(row.values())}** |")
        tot.update(row)
    L.append("| **total** | " + " | ".join(f"**{tot[v]}**" for v in VENUES) + f" | **{sum(tot.values())}** |")
    return "\n".join(L)


def latex(rows_by_project: dict, order: list) -> str:
    projects = [p for p in order if p in rows_by_project] + [p for p in rows_by_project if p not in order]
    L = ["% generated by summarize_defects.py (notebook/012-paper-measurement-studies/defects)",
         r"\begin{tabular}{@{}l" + "r" * len(projects) + r"r@{}}", r"\toprule",
         " & " + " & ".join(projects) + r" & all \\", r"\midrule",
         r"\multicolumn{" + str(len(projects) + 2) + r"}{@{}l}{\emph{Defect class}} \\"]
    allrows = [r for rs in rows_by_project.values() for r in rs]
    for c in CLASSES:
        cells = [sum(1 for r in rows_by_project[p] if r["defect_class"] == c) for p in projects]
        L.append(f"\\quad {c.replace('_', ' ')} & " + " & ".join(map(str, cells)) + f" & {sum(cells)} \\\\")
    L.append(r"\multicolumn{" + str(len(projects) + 2) + r"}{@{}l}{\emph{Discovery venue}} \\")
    for v in VENUES:
        cells = [sum(1 for r in rows_by_project[p] if r["discovery_venue"] == v) for p in projects]
        L.append(f"\\quad {v.replace('_', ' ')} & " + " & ".join(map(str, cells)) + f" & {sum(cells)} \\\\")
    L.append(r"\midrule")
    cells = [len(rows_by_project[p]) for p in projects]
    L.append("Defects (distinct) & " + " & ".join(map(str, cells)) + f" & {sum(cells)} \\\\")
    cells = [sum(1 for r in rows_by_project[p] if r["experiment_ruining_proposed"] == "yes") for p in projects]
    L.append("Proposed experiment-ruining & " + " & ".join(map(str, cells)) + f" & {sum(cells)} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csvs", nargs="+")
    ap.add_argument("--out", default="results")
    ap.add_argument("--order", default="AirStack-core,RAVEN,DFM2,Hummingbird,Shimizu,SwarmCBF")
    ap.add_argument("--verify", action="append", default=[], help="PROJECT=local_repo_path")
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    by_project: dict = {}
    for p in a.csvs:
        for r in load(Path(p)):
            by_project.setdefault(r["project"], []).append(r)
    verify = dict(v.split("=", 1) for v in a.verify)
    unverifiable = []
    for proj, path in verify.items():
        for r in by_project.get(proj, []):
            ok = subprocess.run(["git", "-C", path, "cat-file", "-e", r["commit_sha"] + "^{commit}"],
                                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
            if not ok:
                unverifiable.append(f"{r['defect_id']} {r['commit_sha'][:10]}")
    order = a.order.split(",")
    L = ["# Defect-discovery mining — summary", "",
         "Generated by `summarize_defects.py (notebook/012-paper-measurement-studies/defects)` from the per-project `defects.csv` files "
         "(Stage 2 of the mining protocol in `defect_mining_prompt.md`).", ""]
    allrows = []
    for proj in [p for p in order if p in by_project] + [p for p in by_project if p not in order]:
        rows = by_project[proj]
        allrows += rows
        integ = sum(1 for r in rows if r["defect_class"] in INTEGRATION)
        L += [f"## {proj} — {len(rows)} defects", "", table(rows), "",
              f"Integration-wiring classes (remap/TF/parameter/timing/build): {integ} of {len(rows)} "
              f"({100 * integ / len(rows):.0f}%). Proposed experiment-ruining: "
              + ", ".join(f"{k} {v}" for k, v in Counter(r["experiment_ruining_proposed"] for r in rows).most_common())
              + ". Class confidence: " + ", ".join(f"{k} {v}" for k, v in Counter(r["class_confidence"] for r in rows).most_common())
              + ". Venue confidence: " + ", ".join(f"{k} {v}" for k, v in Counter(r["venue_confidence"] for r in rows).most_common()) + ".", ""]
    integ = sum(1 for r in allrows if r["defect_class"] in INTEGRATION)
    L += [f"## All projects — {len(allrows)} defects", "", table(allrows), "",
          f"Integration-wiring classes: {integ} of {len(allrows)} ({100 * integ / len(allrows):.0f}%).", ""]
    if verify:
        L += ["## SHA verification", "",
              f"{sum(len(by_project.get(p, [])) for p in verify) - len(unverifiable)} of "
              f"{sum(len(by_project.get(p, [])) for p in verify)} rows in verified projects resolve in the local clones."
              + (" Unresolvable: " + ", ".join(unverifiable) if unverifiable else ""), ""]
    (out / "summary.md").write_text("\n".join(L))
    (out / "table_defects.tex").write_text(latex(by_project, order))
    (out / "summary.json").write_text(json.dumps({
        p: {"n": len(rs), "by_class": dict(Counter(r["defect_class"] for r in rs)),
            "by_venue": dict(Counter(r["discovery_venue"] for r in rs)),
            "ruining": dict(Counter(r["experiment_ruining_proposed"] for r in rs))} for p, rs in by_project.items()}, indent=2) + "\n")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
