#!/usr/bin/env python3
# Copyright (c) 2026 Carnegie Mellon University
# MIT License - see LICENSE in the repository root for full text.
"""Generate per-robot compose services for a HETEROGENEOUS fleet (RFC #380 §2).

``deploy.replicas`` can only stamp identical containers, so a fleet whose
robots differ (stack, vehicle, or split placement) needs one compose service
per robot — plus one per (ground host × offboard tenant). This tool writes
them to ``.airstack/generated/docker-compose.fleet.yaml`` (gitignored,
machine-local, regenerated on demand), which ``airstack up --fleet <name>``
includes automatically.

Homogeneous fleets need NO generation: the tool detects homogeneity, says so,
and writes nothing (deploy.replicas + the fleet resolver handle them).

Service shape: self-contained definitions — extending nothing — that copy
robot-desktop's essentials (image, command, network, GPU reservation, mounts)
with **explicit per-robot env**: ROBOT_NAME, ROS_DOMAIN_ID, AIRSTACK_STACK_DIR,
AIRSTACK_STACK_ENTRY, FLEET_CONFIG_FILE (plus VEHICLE / CALIBRATION_DIR).
Explicit ROBOT_NAME means the container's .bashrc skips name resolution
entirely (pre-set env wins — the documented contract).

SPLIT placement: a robot with ``hosts: {offboard: <ground>}`` gets its
``onboard`` entry; the named ground host gets one service per tenant robot
running the SAME stack with ``AIRSTACK_STACK_ENTRY=offboard`` on the fleet's
``gcs_domain`` (mirroring the legacy robot-offboard service).

Output is deterministic: a pure function of the fleet file + checkout layout
(no timestamps; host paths are absolute on purpose — relative bind sources
resolve against ambiguous bases when compose merges ``-f`` files, the same
rule ``tools/module_overlay.py`` follows).

CLI::

    generate_fleet_compose.py <fleet.yaml> [--project-root DIR] [--out PATH]
                              [--check-homogeneous]

Exit 0 always on success; ``--check-homogeneous`` prints ``homogeneous`` or
``heterogeneous`` and writes nothing.
"""
import argparse
import sys
from pathlib import Path

import yaml

_TOOLS_FLEET_DIR = Path(__file__).resolve().parent
if str(_TOOLS_FLEET_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_FLEET_DIR))

from resolve_fleet import (  # noqa: E402
    FleetError,
    fleet_is_homogeneous,
    load_fleet,
    project_root_of,
    resolve_fleet,
    validate_fleet,
)

GENERATED_REL = Path(".airstack/generated/docker-compose.fleet.yaml")
CONTAINER_ROOT = "/root/AirStack"

HEADER = """\
# GENERATED by tools/fleet/generate_fleet_compose.py — DO NOT EDIT (RFC #380 §2).
# Per-robot services for a heterogeneous fleet: deploy.replicas can only stamp
# identical containers, so each robot (and each ground host's offboard tenant)
# gets its own self-contained service with explicit identity/placement env.
# Regenerate: airstack fleet generate <fleet>   (airstack up --fleet <name>
# regenerates and includes this file automatically; profile: fleet).
# Host paths are absolute on purpose: relative bind sources resolve against
# ambiguous bases when compose merges -f files (same rule as the module
# overlay compose).
"""

# The robot-desktop bring-up command, copied verbatim (docker-compose.yaml is
# the source of truth; the AUTONOMY_ROLE arg is ignored whenever a stack dir
# is set — every fleet service sets one).
ROBOT_COMMAND = (
    "bash -c \" "
    "if [ -z \\\"$$DISPLAY\\\" ] && command -v Xvfb >/dev/null 2>&1; then "
    "tmux new -d -s xvfb 'Xvfb :99 -screen 0 1280x720x24 -ac +extension GLX +render -noreset 2>&1 | tee /tmp/xvfb.log'; "
    "export DISPLAY=:99; "
    "for i in 1 2 3 4 5 6 7 8 9 10; do [ -e /tmp/.X11-unix/X99 ] && break; sleep 1; done; "
    "fi; "
    "service ssh restart; "
    "tmux new -d -s bringup; "
    "if [ $$AUTOLAUNCH == 'true' ]; then "
    "tmux send-keys -t bringup:0.0 'bws && sws && ros2 launch $$LAUNCH_PACKAGE robot.launch.xml role:=$$AUTONOMY_ROLE' ENTER; "
    "fi; "
    "sleep infinity\""
)


def _base_volumes(root):
    """robot_base's bind mounts (robot/docker/robot-base-docker-compose.yaml),
    with host sides made absolute."""
    r = str(root)
    return [
        "$HOME/.Xauthority:/.Xauthority",
        "/tmp/.X11-unix:/tmp/.X11-unix",
        f"{r}/robot/docker/.dev:/root/.dev:rw",
        f"{r}/common/.bash_profile:/root/.bash_profile:rw",
        f"{r}/robot/docker/.bashrc:/root/.bashrc:rw",
        f"{r}/common/inputrc:/etc/inputrc:rw",
        f"{r}/common/.tmux.conf:/root/.tmux.conf:rw",
        f"{r}/robot/docker/robot_name_map:/root/AirStack/robot/docker/robot_name_map:rw",
        f"{r}/common/ros_packages:/root/AirStack/robot/ros_ws/src/common:rw",
        f"{r}/common/fastdds.xml:/root/AirStack/robot/ros_ws/src/fastdds.xml",
        f"{r}/robot/ros_ws:/root/AirStack/robot/ros_ws:rw",
        f"{r}/stacks:/root/AirStack/stacks:rw",
        f"{r}/robot/bags:/bags:rw",
        # fleet + vehicle configs (FLEET_CONFIG_FILE, CALIBRATION_DIR)
        f"{r}/config:/root/AirStack/config:ro",
        f"{r}/tools/fleet:/root/AirStack/tools/fleet:ro",
        # generated artifacts split-stack entries read at launch (bridge-derived
        # DDS-router configs)
        f"{r}/.airstack/generated:/root/AirStack/.airstack/generated:ro",
    ]


def _common_environment():
    """Env shared by every fleet service (robot_base + robot-desktop essentials,
    interpolated from .env at compose time exactly like the originals)."""
    return [
        "DISPLAY=${DISPLAY}",
        "QT_X11_NO_MITSHM=1",
        "QT_QPA_PLATFORM",
        "RECORD_BAGS=${RECORD_BAGS}",
        "LOG_CONFIG=${LOG_CONFIG:-log.yaml}",
        "URDF_FILE=${URDF_FILE}",
        "OFFBOARD_BASE_PORT=${OFFBOARD_BASE_PORT}",
        "ONBOARD_BASE_PORT=${ONBOARD_BASE_PORT}",
        "ROBOT_NAME_MAP_CONFIG_FILE=${ROBOT_NAME_MAP_CONFIG_FILE:-default_robot_name_map.yaml}",
        "DEBUG_RVIZ=${DEBUG_RVIZ:-false}",
        "AUTOLAUNCH=${AUTOLAUNCH:-true}",
        "NVIDIA_DRIVER_CAPABILITIES=all",
        "SIM_IP=${SIM_IP:-172.31.0.200}",
        # role is ignored whenever a stack dir is set (robot.launch.xml); kept
        # non-empty so the shared bring-up command's role:=$AUTONOMY_ROLE arg
        # stays well-formed.
        "AUTONOMY_ROLE=full",
    ]


def _identity_environment(robot_name, domain_id, stack_rel, entry,
                          fleet_container_path, vehicle, calibration_rel):
    return [
        f"ROBOT_NAME={robot_name}",
        f"ROS_DOMAIN_ID={domain_id}",
        f"AIRSTACK_STACK_DIR={CONTAINER_ROOT}/{stack_rel}",
        f"AIRSTACK_STACK_ENTRY={entry}",
        f"FLEET_CONFIG_FILE={fleet_container_path}",
        f"VEHICLE={vehicle}",
        "CALIBRATION_DIR=" + (
            f"{CONTAINER_ROOT}/{calibration_rel}" if calibration_rel else ""
        ),
    ]


def _service_skeleton(root):
    return {
        "profiles": ["fleet"],
        "image": "${PROJECT_DOCKER_REGISTRY}/${PROJECT_NAME}:v${VERSION}_robot-x86-64_${DOCKER_IMAGE_BUILD_MODE}",
        "stdin_open": True,
        "tty": True,
        "privileged": True,
        "command": ROBOT_COMMAND,
        "networks": ["airstack_network"],
        "volumes": _base_volumes(root),
        "deploy": {
            "resources": {
                "reservations": {
                    "devices": [
                        {"driver": "nvidia", "count": 1, "capabilities": ["gpu"]}
                    ]
                }
            }
        },
    }


def build_compose(fleet, root, fleet_rel):
    """Compose dict for a heterogeneous fleet. Raises FleetError on problems."""
    resolved = resolve_fleet(fleet, root)
    fleet_container_path = f"{CONTAINER_ROOT}/{fleet_rel}"
    services = {}

    for robot in resolved["robots"]:
        svc = _service_skeleton(root)
        svc["environment"] = _common_environment() + [
            "LAUNCH_PACKAGE=desktop_bringup",  # desktop parity: adds RViz
        ] + _identity_environment(
            robot["robot_name"], robot["domain_id"], robot["stack"],
            robot["entry"], fleet_container_path, robot["vehicle"],
            robot["calibration_dir"],
        )
        # Same host port ranges as robot-desktop: docker binds the first free
        # port in the range per container.
        svc["ports"] = ["2223-2243:22", "8767-8787:8765"]
        services[robot["robot_name"]] = svc

    gcs_domain = resolved["network"]["gcs_domain"]
    for host, cfg in resolved["ground"].items():
        for tenant in cfg["tenants"]:
            svc = _service_skeleton(root)
            # Mirrors the legacy robot-offboard service: no ssh/foxglove ports,
            # autonomy_bringup (no per-robot RViz), gcs domain, offboard entry
            # of the SAME split stack, serving one tenant robot.
            svc["environment"] = _common_environment() + [
                "LAUNCH_PACKAGE=autonomy_bringup",
            ] + _identity_environment(
                tenant["robot_name"], gcs_domain, tenant["stack"],
                tenant["role"], fleet_container_path, "-", "",
            )
            # VEHICLE is meaningless on a ground host; drop the placeholder.
            svc["environment"] = [
                e for e in svc["environment"] if e != "VEHICLE=-"
            ]
            services[f"{host}-{tenant['robot_name']}"] = svc

    return {
        "x-airstack-fleet": fleet_rel,
        "services": services,
    }


def render(compose):
    return HEADER + yaml.safe_dump(
        compose, sort_keys=True, default_flow_style=False, width=100
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate per-robot compose services for a heterogeneous "
                    "fleet (RFC #380 §2)."
    )
    parser.add_argument("fleet_file", help="path to config/fleets/<name>.yaml")
    parser.add_argument("--project-root", default=None)
    parser.add_argument("--out", default=None,
                        help="output path (default: <root>/.airstack/generated/"
                             "docker-compose.fleet.yaml)")
    parser.add_argument("--check-homogeneous", action="store_true",
                        help="print 'homogeneous' or 'heterogeneous'; write nothing")
    args = parser.parse_args(argv)

    root = Path(args.project_root) if args.project_root else project_root_of(args.fleet_file)
    fleet_path = Path(args.fleet_file).resolve()
    try:
        fleet_rel = str(fleet_path.relative_to(root.resolve()))
    except ValueError:
        fleet_rel = f"config/fleets/{fleet_path.name}"

    try:
        fleet = load_fleet(fleet_path)
        errors = validate_fleet(fleet, root)
        if errors:
            for err in errors:
                print(f"Error: {err}", file=sys.stderr)
            return 1

        homogeneous = fleet_is_homogeneous(fleet, root)
        if args.check_homogeneous:
            print("homogeneous" if homogeneous else "heterogeneous")
            return 0
        if homogeneous:
            n = len(fleet["robots"])
            print(
                f"Fleet '{fleet_path.stem}' is homogeneous ({n} identical robot(s)) — "
                f"deploy.replicas handles it: use NUM_ROBOTS={n} "
                f"(airstack up --fleet {fleet_path.stem} derives it). "
                f"No generation needed."
            )
            return 0

        out = Path(args.out) if args.out else root / GENERATED_REL
        out.parent.mkdir(parents=True, exist_ok=True)
        content = render(build_compose(fleet, root, fleet_rel))
        out.write_text(content, encoding="utf-8")
        n_services = len(build_compose(fleet, root, fleet_rel)["services"])
        print(f"Wrote {out} ({n_services} service(s), profile 'fleet').")
        return 0
    except FleetError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
