name: ROS 2 Workspace Test
description: Test packages in a ROS 2 workspace
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        source install/setup.bash
        colcon test --event-handlers console_cohesion+ --pytest-with-coverage --return-code-on-test-failure