name: ROS 2 Workspace Setup
description: Setup tools and dependencies for a ROS 2 workspace
inputs:
  distro:
    description: The ROS 2 distribution to be used
    default: iron
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list

    - shell: bash
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions python3-rosdep

    - shell: bash
      run: |
        sudo rosdep init
        rosdep update
        rosdep install -y --rosdistro ${{ inputs.distro }} --from-paths . --ignore-src

    - shell: bash
      run: |
        source /opt/ros/${{ inputs.distro }}/setup.bash
        colcon build --packages-skip-regex '.*'


